using Content.Client._Oxyd.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.NeoTheology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.NeoTheology.UI;

/// <summary>
/// Biogenerator screen (Eris <c>nt_biogen.tmpl</c>): a status block of spec rows — machine
/// state, generator on/off, fuel, output power, and fouling.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class BiogeneratorConsoleWindow : FancyWindow
{
    private readonly Label _operationalValue = new();
    private readonly Label _generatorValue = new();
    private readonly Label _fuelValue = new();
    private readonly Label _powerValue = new();
    private readonly Label _dirtinessValue = new();

    public BiogeneratorConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Body.PanelOverride = new StyleBoxFlat(ErisNanoColors.BodyBg);
        AddRow(Loc.GetString("oxyd-biogenerator-console-status"), _operationalValue);
        AddRow(Loc.GetString("oxyd-biogenerator-console-generator"), _generatorValue);
        AddRow(Loc.GetString("oxyd-biogenerator-console-fuel"), _fuelValue);
        AddRow(Loc.GetString("oxyd-biogenerator-console-power"), _powerValue);
        AddRow(Loc.GetString("oxyd-biogenerator-console-dirtiness"), _dirtinessValue);
    }

    private void AddRow(string field, Label value)
    {
        var row = new ErisSpecRow(field, 160f);
        row.AddValue(value);
        Content.AddChild(row);
    }

    public void UpdateState(BiogeneratorConsoleState state)
    {
        _operationalValue.Text = Loc.GetString(state.Operational
            ? "oxyd-console-operational"
            : "oxyd-console-offline");
        _operationalValue.FontColorOverride = state.Operational
            ? ErisNanoColors.GoodText
            : ErisNanoColors.BadText;

        _generatorValue.Text = Loc.GetString(state.GeneratorOn ? "oxyd-console-on" : "oxyd-console-off");
        _generatorValue.FontColorOverride = state.GeneratorOn
            ? ErisNanoColors.GoodText
            : ErisNanoColors.BadText;

        _fuelValue.Text = Loc.GetString("oxyd-biogenerator-console-fuel-value",
            ("amount", state.FuelAmount.ToString("0.#")));
        _fuelValue.FontColorOverride = ErisNanoColors.Text;

        _powerValue.Text = Loc.GetString("oxyd-biogenerator-console-power-value",
            ("power", state.TargetPower.ToString("0")),
            ("maximum", state.MaxTargetPower.ToString("0")));
        _powerValue.FontColorOverride = ErisNanoColors.Text;

        var fouled = state.Dirtiness > 0.25f;
        _dirtinessValue.Text = Loc.GetString("oxyd-biogenerator-console-dirtiness-value",
            ("percent", (state.Dirtiness * 100f).ToString("0")));
        _dirtinessValue.FontColorOverride = fouled
            ? ErisNanoColors.WarningText
            : ErisNanoColors.GoodText;
    }
}
