using Content.Client._Oxyd.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.NeoTheology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.NeoTheology.UI;

/// <summary>
/// Bioreactor metrics console (Eris <c>bioreactor.tmpl</c>): a status block of spec rows —
/// machine state, chamber door, chamber solution, breach, and a contents count.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class BioreactorConsoleWindow : FancyWindow
{
    private readonly Label _operationalValue = new();
    private readonly Label _chamberValue = new();
    private readonly Label _solutionValue = new();
    private readonly Label _breachValue = new();
    private readonly Label _contentsValue = new();

    public BioreactorConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Body.PanelOverride = new StyleBoxFlat(ErisNanoColors.BodyBg);
        AddRow(Loc.GetString("oxyd-bioreactor-console-status"), _operationalValue);
        AddRow(Loc.GetString("oxyd-bioreactor-console-chamber"), _chamberValue);
        AddRow(Loc.GetString("oxyd-bioreactor-console-solution"), _solutionValue);
        AddRow(Loc.GetString("oxyd-bioreactor-console-breach"), _breachValue);
        AddRow(Loc.GetString("oxyd-bioreactor-console-contents"), _contentsValue);
    }

    private void AddRow(string field, Label value)
    {
        var row = new ErisSpecRow(field, 160f);
        row.AddValue(value);
        Content.AddChild(row);
    }

    public void UpdateState(BioreactorConsoleState state)
    {
        SetStatus(_operationalValue, state.Operational,
            "oxyd-console-operational", "oxyd-console-offline");
        SetStatus(_chamberValue, state.ChamberClosed,
            "oxyd-console-closed", "oxyd-console-open");
        SetStatus(_solutionValue, state.ChamberSolution,
            "oxyd-console-filled", "oxyd-console-required");
        SetStatus(_breachValue, state.ChamberBreached,
            "oxyd-console-breached", "oxyd-console-sealed", invert: true);
        _contentsValue.Text = state.ChamberContents.ToString();
        _contentsValue.FontColorOverride = state.ChamberContents > 0
            ? ErisNanoColors.ItemLabelText
            : ErisNanoColors.LabelText;
    }

    private static void SetStatus(Label label, bool flag, string yes, string no, bool invert = false)
    {
        var good = invert ? !flag : flag;
        label.Text = Loc.GetString(flag ? yes : no);
        label.FontColorOverride = good ? ErisNanoColors.GoodText : ErisNanoColors.BadText;
    }
}
