using Content.Client._Oxyd.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.NeoTheology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.NeoTheology.UI;

[GenerateTypedNameReferences]
public sealed partial class EyeOfTheProtectorWindow : FancyWindow
{
    public EyeOfTheProtectorWindow()
    {
        RobustXamlLoader.Load(this);

        Body.PanelOverride = new StyleBoxFlat(ErisNanoColors.BodyBg);
        ObservationFieldLabel.FontColorOverride = ErisNanoColors.ItemLabelText;
        ArmamentsFieldLabel.FontColorOverride = ErisNanoColors.ItemLabelText;
        MiracleFieldLabel.FontColorOverride = ErisNanoColors.ItemLabelText;
        ObservationFieldLabel.Text = Loc.GetString("oxyd-eotp-observation-field");
        ArmamentsFieldLabel.Text = Loc.GetString("oxyd-eotp-armaments-field");
        MiracleFieldLabel.Text = Loc.GetString("oxyd-eotp-miracle-field");
    }

    public void UpdateState(EyeOfTheProtectorState state)
    {
        ObservationLabel.Text = ((int) state.Observation).ToString();
        ArmamentsLabel.Text = Loc.GetString("oxyd-eotp-armaments-value",
            ("points", state.ArmamentsPoints),
            ("maximum", state.MaxArmamentsPoints));
        MiracleLabel.Text = state.MiracleCooldown <= System.TimeSpan.Zero
            ? Loc.GetString("oxyd-eotp-miracle-ready")
            : state.MiracleCooldown.ToString(@"mm\:ss");
    }
}
