using System.Globalization;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access;
using Content.Shared._Oxyd.NeoTheology;
using Content.Shared._Oxyd.NeoTheology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Oxyd.NeoTheology.UI;

[GenerateTypedNameReferences]
public sealed partial class LitanyWindow : FancyWindow
{
    private const double HolinessTolerance = 0.000001d;
    private const int MaximumPlainTextScalars = 512;
    private const int AllCategoriesId = -1;

    [Dependency] private IGameTiming _gameTiming = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private LitanyViewerSnapshot? _snapshot;
    private LitanyViewerEntry? _selectedEntry;
    private ProtoId<LitanyPrototype>? _selectedLitany;
    private LitanyCategory? _categoryFilter;
    private bool _suppressCategorySelect;
    private LitanyBusyState? _busyState;
    private string? _choiceRequestId;
    private TimeSpan _choiceExpiresAt;
    private List<LitanyChoiceOption> _choiceOptions = new();
    private string? _resultText;
    private uint _resultRevision;
    private bool _hasRolePresentation;
    private bool _hasCruciform;
    private NeoTheologyClearance _clearance;

    public event Action<ProtoId<LitanyPrototype>, uint, string?>? BeginLitany;
    public event Action<string, List<string>, string?, string?>? SubmitChoices;
    public event Action<string>? CancelLitany;

    public LitanyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CategorySelector.Prefix = "Category:";

        SearchBar.OnTextChanged += _ => RefreshEntryList(preserveSelection: false);
        CategorySelector.OnItemSelected += args =>
        {
            if (_suppressCategorySelect)
                return;

            _categoryFilter = args.Id == AllCategoriesId
                ? null
                : (LitanyCategory?) (args.Id - 1);
            RefreshEntryList(preserveSelection: false);
        };

        BeginButton.OnPressed += _ => BeginSelectedLitany();
        SubmitChoiceButton.OnPressed += _ => SubmitPendingChoices();
        CancelButton.OnPressed += _ => CancelPendingRequest();

        ChoiceList.OnItemSelected += _ => UpdateChoiceControls();
        ChoiceList.OnItemDeselected += _ => UpdateChoiceControls();

        PlainTextEdit.IsValid = IsPlainTextLengthValid;
        PlainTextEdit.OnTextChanged += _ => UpdatePlainTextCount();

        UpdatePlainTextCount();
    }

    /// <summary>
    /// Supports the original BUI state path while servers migrate to the
    /// actor-targeted snapshot message. The state contains no actor or entity
    /// identity, and the server remains authoritative for every decision.
    /// </summary>
    public void UpdateState(LitanyViewerSnapshot snapshot)
    {
        if (_snapshot is not null && snapshot.Revision < _snapshot.Revision)
            return;

        _hasRolePresentation = false;
        var catalogChanged = _snapshot is null || CatalogChanged(_snapshot.Entries, snapshot.Entries);
        _snapshot = snapshot;

        if (catalogChanged)
            RefreshCategories();

        UpdateProfilePresentation();
        RefreshEntryList(preserveSelection: true);
        UpdateBusyPresentation();
    }

    /// <summary>
    /// Applies the private viewer snapshot sent as a BUI message. Only this
    /// viewer's role, resource values and entry availability are rendered.
    /// </summary>
    public void UpdateSnapshot(LitanyViewerSnapshotMessage snapshot)
    {
        if (_snapshot is not null && snapshot.Revision < _snapshot.Revision)
            return;

        _busyState = snapshot.BusyState;

        var role = snapshot.RolePresentation;
        UpdateState(new LitanyViewerSnapshot(
            snapshot.Revision,
            snapshot.Holiness,
            snapshot.RegenerationPerSecond,
            role.Profile,
            role.Active,
            snapshot.Entries,
            null,
            snapshot.Cap));

        // UpdateState also supports the legacy state path and clears this
        // marker, so apply the actor-targeted role presentation after it runs.
        _hasRolePresentation = true;
        _hasCruciform = role.HasCruciform;
        _clearance = role.Clearance;
        UpdateProfilePresentation();

        if (_busyState is null)
            ClearChoiceSnapshot();
        else if (!string.Equals(_choiceRequestId, _busyState.RequestId, StringComparison.Ordinal))
            ClearChoiceSnapshot();

        UpdateBusyPresentation();
    }

    /// <summary>
    /// Displays the server-authored choice labels and stores only their opaque
    /// tokens in ItemList metadata. Labels are rendered as plain text and are
    /// never resolved into entities or identifiers on the client.
    /// </summary>
    public void UpdateChoiceSnapshot(LitanyChoiceSnapshotMessage snapshot)
    {
        // The viewer-state revision bumps on every bearer Dirty (holiness regen
        // included), so it can overtake a choice snapshot still in flight. Only
        // reject stale revisions for the request we already accepted.
        if (_snapshot is not null && snapshot.Revision < _snapshot.Revision
            && string.Equals(_choiceRequestId, snapshot.RequestId, StringComparison.Ordinal))
            return;

        if (_busyState is not null && !string.Equals(_busyState.RequestId, snapshot.RequestId, StringComparison.Ordinal))
            return;

        var requestChanged = !string.Equals(_choiceRequestId, snapshot.RequestId, StringComparison.Ordinal);
        var selectedTokens = requestChanged
            ? new HashSet<string>(StringComparer.Ordinal)
            : ChoiceList.GetSelected()
                .Select(item => item.Metadata)
                .OfType<string>()
                .ToHashSet(StringComparer.Ordinal);

        _choiceRequestId = snapshot.RequestId;
        _choiceExpiresAt = snapshot.ExpiresAt;
        _choiceOptions = snapshot.AllowedChoices;
        RebuildChoiceList(selectedTokens);
        UpdateChoiceControls();
    }

    /// <summary>
    /// Updates the local progress presentation from server timestamps. No
    /// client-side effect or completion is inferred from this message.
    /// </summary>
    public void UpdateProgress(LitanyProgressMessage progress)
    {
        if (_snapshot is not null && progress.Revision < _snapshot.Revision)
            return;
        if (_busyState is not null && !string.Equals(_busyState.RequestId, progress.RequestId, StringComparison.Ordinal))
            return;

        _busyState = new LitanyBusyState(
            progress.RequestId,
            progress.Litany,
            progress.Stage,
            progress.StartedAt,
            progress.EndsAt,
            progress.CanCancel);
        UpdateBusyPresentation();
    }

    /// <summary>
    /// Shows the server-provided result. A result for an older request cannot
    /// clear a newer busy or choice state.
    /// </summary>
    public void UpdateResult(LitanyResultMessage result)
    {
        // Begin and choice acknowledgments do not end the cast or replace its progress.
        if (!result.IsFinal)
            return;

        if (_snapshot is not null && result.Revision < _snapshot.Revision)
            return;

        _resultRevision = result.Revision;
        _resultText = result.Success
            ? result.Reason is { } successReason
                ? Loc.GetString(successReason)
                : Loc.GetString("oxyd-litany-success")
            : result.Reason is { } reason
                ? Loc.GetString("oxyd-litany-failed", ("reason", Loc.GetString(reason)))
                : Loc.GetString("oxyd-litany-failed", ("reason", "Unknown reason"));

        if (result.RequestId is { } requestId &&
            (string.Equals(requestId, _busyState?.RequestId, StringComparison.Ordinal)
             || string.Equals(requestId, _choiceRequestId, StringComparison.Ordinal)))
        {
            _busyState = null;
            ClearChoiceSnapshot();
        }

        UpdateBusyPresentation();
    }

    public override void Close()
    {
        // Closing is deliberately not cancellation. The explicit Cancel button
        // is the only client action that emits CancelLitany.
        base.Close();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProgressPresentation();
        if (_selectedEntry is { } entry && TryGetLitany(entry, out var litany))
            UpdateCooldownLabel(entry, litany);
        if (_choiceRequestId is not null)
        {
            UpdateChoiceExpiryLabel();
            if (ChoiceExpired())
                SubmitChoiceButton.Disabled = true;
        }
    }

    /// <summary>
    /// Sends cancellation only for the current server-issued request and only
    /// when the server marked that request cancellable.
    /// </summary>
    public void CancelPendingRequest()
    {
        var requestId = _busyState is { CanCancel: true } busy
            ? busy.RequestId
            : _choiceRequestId;
        if (requestId is null)
            return;

        CancelLitany?.Invoke(requestId);
        _busyState = null;
        ClearChoiceSnapshot();
        UpdateBusyPresentation();
    }

    private void RefreshCategories()
    {
        // Clear/TrySelectId re-fire OnItemSelected; suppress it so a snapshot
        // refresh can't stomp the user's filter choice.
        _suppressCategorySelect = true;
        try
        {
            CategorySelector.Clear();
            CategorySelector.AddItem("All", AllCategoriesId);

            if (_snapshot is null)
                return;

            var categories = new HashSet<LitanyCategory>();
            foreach (var entry in _snapshot.Entries)
            {
                if (TryGetLitany(entry, out var litany))
                    categories.Add(litany.Category);
            }

            foreach (var category in categories.OrderBy(category => (int) category))
                CategorySelector.AddItem(category.ToString(), (int) category + 1);

            if (_categoryFilter is { } filter && !CategorySelector.TrySelectId((int) filter + 1))
            {
                _categoryFilter = null;
                CategorySelector.TrySelectId(AllCategoriesId);
            }
            else if (_categoryFilter is null)
            {
                CategorySelector.TrySelectId(AllCategoriesId);
            }
        }
        finally
        {
            _suppressCategorySelect = false;
        }
    }

    private void RefreshEntryList(bool preserveSelection)
    {
        if (_snapshot is null)
            return;

        var scrollValue = EntryScroll.GetScrollValue();
        var filteredEntries = GetFilteredEntries().ToList();
        LitanyViewerEntry? entryToSelect = null;

        if (preserveSelection && _selectedLitany is { } selectedId)
        {
            entryToSelect = _snapshot.Entries.FirstOrDefault(entry => entry.Litany.Equals(selectedId));
        }

        if (!preserveSelection || entryToSelect is null && _selectedLitany is null)
            entryToSelect = filteredEntries.FirstOrDefault();

        if (!preserveSelection && entryToSelect is null)
            _selectedLitany = null;

        EntryList.DisposeAllChildren();
        EmptyCatalogLabel.Visible = filteredEntries.Count == 0;

        var buttonGroup = new ButtonGroup();
        foreach (var entry in filteredEntries)
        {
            var name = GetLitanyName(entry);
            var category = GetLitanyCategory(entry);
            var suffix = entry.Available ? string.Empty : " [Unavailable]";
            var button = new Button
            {
                Text = $"{category}: {name}{suffix}",
                HorizontalExpand = true,
                MinHeight = 30,
                ToggleMode = true,
                Group = buttonGroup,
                Pressed = entryToSelect is not null && entry.Litany.Equals(entryToSelect.Litany),
                ToolTip = GetLitanyDescription(entry),
                StyleClasses = { "ButtonSquare" },
            };

            button.OnPressed += _ => SelectEntry(entry);
            EntryList.AddChild(button);
        }

        if (entryToSelect is null)
        {
            _selectedEntry = null;
            UpdateDetails();
        }
        else
        {
            SelectEntry(entryToSelect, refreshList: false);
        }

        EntryScroll.SetScrollValue(scrollValue);
    }

    private IEnumerable<LitanyViewerEntry> GetFilteredEntries()
    {
        if (_snapshot is null)
            return Enumerable.Empty<LitanyViewerEntry>();

        var search = SearchBar.Text.Trim();
        return _snapshot.Entries
            .Where(entry => _categoryFilter is null || GetLitanyCategory(entry) == _categoryFilter)
            .Where(entry => string.IsNullOrEmpty(search)
                            || GetLitanyName(entry).Contains(search, StringComparison.CurrentCultureIgnoreCase)
                            || GetLitanyDescription(entry).Contains(search, StringComparison.CurrentCultureIgnoreCase))
            .OrderBy(entry => (int) GetLitanyCategory(entry))
            .ThenBy(GetLitanyName, StringComparer.CurrentCultureIgnoreCase)
            .ThenBy(entry => entry.Litany.ToString(), StringComparer.Ordinal);
    }

    private void SelectEntry(LitanyViewerEntry entry, bool refreshList = true)
    {
        _selectedLitany = entry.Litany;
        _selectedEntry = entry;
        UpdateDetails();

        if (refreshList)
            RefreshEntryList(preserveSelection: true);
    }

    private void UpdateProfilePresentation()
    {
        if (_snapshot is not { } snapshot)
            return;

        var profile = GetProfile(snapshot.Profile);
        var profileName = profile is null ? "—" : Loc.GetString(profile.Name);
        var maximumHoliness = snapshot.Cap > 0 ? snapshot.Cap : GetMaximumHoliness(profile);

        HolinessLabel.Text = Loc.GetString("oxyd-cruciform-holiness",
            ("current", snapshot.Holiness.ToString("0.##")),
            ("maximum", maximumHoliness.ToString("0.##")));
        RegenerationLabel.Text = $"Regeneration: {snapshot.RegenerationPerSecond.ToString("0.####", CultureInfo.CurrentCulture)}/s";

        var hasCruciform = _hasRolePresentation
            ? _hasCruciform
            : snapshot.Active || profile is not null;
        RankLabel.Text = Loc.GetString("oxyd-cruciform-rank",
            ("rank", hasCruciform ? profileName : "—"));
        var clearanceName = _clearance switch
        {
            NeoTheologyClearance.Clergy => Loc.GetString("oxyd-cruciform-clearance-clergy"),
            NeoTheologyClearance.Common => Loc.GetString("oxyd-cruciform-clearance-common"),
            _ => Loc.GetString("oxyd-cruciform-clearance-none"),
        };
        ClearanceLabel.Text = Loc.GetString("oxyd-cruciform-clearance",
            ("clearance", hasCruciform ? clearanceName : "—"));

        HolinessBar.MaxValue = maximumHoliness > 0
            ? (float) Math.Min(maximumHoliness, float.MaxValue)
            : 1f;
        HolinessBar.Value = double.IsFinite(snapshot.Holiness)
            ? (float) Math.Clamp(snapshot.Holiness, 0d, Math.Max(1d, maximumHoliness))
            : 0f;
    }

    private void UpdateDetails()
    {
        if (_selectedEntry is not { } entry)
        {
            SelectedName.Text = "Select a litany";
            SelectedDescription.SetMessage(string.Empty);
            PhraseLabel.SetMessage(string.Empty);
            CostLabel.Text = string.Empty;
            CooldownLabel.Text = string.Empty;
            CastDurationLabel.Text = string.Empty;
            TargetLabel.SetMessage(string.Empty);
            AvailabilityLabel.SetMessage(string.Empty);
            BeginButton.Disabled = true;
            UpdateChoiceControls();
            return;
        }

        if (!TryGetLitany(entry, out var litany))
        {
            SelectedName.Text = entry.Litany.ToString();
            SelectedDescription.SetMessage(string.Empty);
            PhraseLabel.SetMessage(string.Empty);
            CostLabel.Text = string.Empty;
            CooldownLabel.Text = string.Empty;
            CastDurationLabel.Text = string.Empty;
            TargetLabel.SetMessage(string.Empty);
            AvailabilityLabel.SetMessage(string.Empty);
            BeginButton.Disabled = true;
            UpdateChoiceControls();
            return;
        }

        SelectedName.Text = Loc.GetString(litany.Name);
        SelectedDescription.SetMessage(Loc.GetString(litany.Description));
        // Prototype-set values are read from the prototype, not duplicated over the wire.
        PhraseLabel.SetMessage(Loc.GetString("oxyd-litany-ui-phrase", ("phrase", litany.Phrase)));
        CostLabel.Text = Loc.GetString("oxyd-litany-ui-cost", ("cost", litany.Cost.ToString("0.##")));
        UpdateCooldownLabel(entry, litany);
        CastDurationLabel.Text = Loc.GetString("oxyd-litany-ui-extra-delay", ("duration", FormatDuration(litany.ExtraDelay)));
        TargetLabel.SetMessage(Loc.GetString("oxyd-litany-ui-target", ("target", FormatTargetMode(litany.TargetMode))));

        if (entry.Available)
        {
            AvailabilityLabel.SetMessage(Loc.GetString("oxyd-litany-ui-available"));
        }
        else
        {
            var reason = entry.UnavailableReason is { } reasonId
                ? Loc.GetString(reasonId)
                : "This litany is not available to the viewer.";
            AvailabilityLabel.SetMessage(Loc.GetString("oxyd-litany-ui-unavailable", ("reason", reason)));
        }

        UpdateChoiceControls();
    }

    private void UpdateCooldownLabel(LitanyViewerEntry entry, LitanyPrototype litany)
    {
        CooldownLabel.Text = Loc.GetString("oxyd-litany-ui-cooldown", ("duration", FormatDuration(litany.CooldownDuration)));
        var remaining = entry.CooldownEndsAt - _gameTiming.CurTime;
        if (remaining > TimeSpan.Zero)
            CooldownLabel.Text += $" ({FormatDuration(remaining)} remaining)";
    }

    private void UpdateChoiceControls()
    {
        var requiresChoice = _selectedEntry is { } entry && RequiresChoice(entry);
        var hasChoiceRequest = _choiceRequestId is not null;
        var choosing = hasChoiceRequest && (_busyState is null || _busyState.Stage == LitanyCastStage.Choosing);

        ChoiceContainer.Visible = requiresChoice || hasChoiceRequest;
        ChoiceInstructionLabel.Text = hasChoiceRequest
            ? "Select one or more server-provided choices."
            : requiresChoice
                ? "The server will provide eligible choices after Begin."
                : string.Empty;
        ChoiceList.Visible = hasChoiceRequest && _choiceOptions.Count > 0;
        ChoiceExpiryLabel.Visible = hasChoiceRequest;
        RecipeRow.Visible = hasChoiceRequest;
        PlainTextRow.Visible = hasChoiceRequest;
        PlainTextCountLabel.Visible = hasChoiceRequest;
        PendingRequestLabel.Visible = hasChoiceRequest;

        SubmitChoiceButton.Visible = hasChoiceRequest;
        SubmitChoiceButton.Disabled = !hasChoiceRequest || !choosing || ChoiceExpired();
        CancelButton.Visible = _busyState is not null || hasChoiceRequest;
        CancelButton.Disabled = _busyState is not { CanCancel: true } && !hasChoiceRequest;

        if (hasChoiceRequest)
        {
            UpdateChoiceExpiryLabel();
            PendingRequestLabel.Text = "Server request is active; its ID remains opaque.";
        }
        else
        {
            ChoiceExpiryLabel.Text = string.Empty;
            PendingRequestLabel.Text = string.Empty;
        }

        BeginButton.Disabled = !CanBeginSelectedLitany();
    }

    private void RebuildChoiceList(HashSet<string>? selectedTokens = null)
    {
        selectedTokens ??= ChoiceList.GetSelected()
            .Select(item => item.Metadata)
            .OfType<string>()
            .ToHashSet(StringComparer.Ordinal);

        ChoiceList.Clear();
        foreach (var option in _choiceOptions)
        {
            // DisplayLabel is server-authored plain text. Token is retained only
            // as opaque metadata and is never shown or resolved by the client.
            var item = ChoiceList.AddItem(option.DisplayLabel, metadata: option.Token);
            if (selectedTokens.Contains(option.Token))
                item.Selected = true;
        }
    }

    private void BeginSelectedLitany()
    {
        if (_snapshot is null || _selectedEntry is not { } entry || !CanBeginSelectedLitany())
            return;

        // Initial target selection is server-driven. The optional token in the
        // message remains null until a future server contract supplies one.
        BeginLitany?.Invoke(entry.Litany, _snapshot.Revision, null);
    }

    private void SubmitPendingChoices()
    {
        if (_choiceRequestId is not { } requestId || ChoiceExpired())
            return;

        var tokens = ChoiceList.GetSelected()
            .Select(item => item.Metadata as string)
            .Where(token => token is not null)
            .Cast<string>()
            .ToList();
        var recipeId = string.IsNullOrEmpty(RecipeIdEdit.Text) ? null : RecipeIdEdit.Text;
        var plainText = string.IsNullOrEmpty(PlainTextEdit.Text) ? null : PlainTextEdit.Text;

        SubmitChoices?.Invoke(requestId, tokens, recipeId, plainText);
    }

    private void ClearChoiceSnapshot()
    {
        _choiceRequestId = null;
        _choiceExpiresAt = default;
        _choiceOptions = new List<LitanyChoiceOption>();
        ChoiceList.Clear();
        RecipeIdEdit.Clear();
        PlainTextEdit.Clear();
    }

    private void UpdateBusyPresentation()
    {
        UpdateProgressPresentation();
        UpdateChoiceControls();

        if (_snapshot is null)
            return;

        if (_busyState is not null)
        {
            StatusLabel.Text = $"{FormatStage(_busyState.Stage)}: {GetBusyLitanyName(_busyState)}";
            return;
        }

        if (_resultText is not null && _resultRevision >= _snapshot.Revision)
        {
            StatusLabel.Text = _resultText;
            return;
        }

        var hasCruciform = _hasRolePresentation
            ? _hasCruciform
            : _snapshot.Active || GetProfile(_snapshot.Profile) is not null;
        StatusLabel.Text = _snapshot.BusyReason ?? (_snapshot.Active
            ? string.Empty
            : hasCruciform
                ? Loc.GetString("oxyd-cruciform-inactive")
                : Loc.GetString("oxyd-cruciform-no-implant"));
    }

    private void UpdateProgressPresentation()
    {
        if (_busyState is not { } busy)
        {
            CastProgressBar.Visible = false;
            CastProgressLabel.Text = string.Empty;
            return;
        }

        var duration = busy.EndsAt - busy.StartedAt;
        var fraction = duration <= TimeSpan.Zero
            ? 1f
            : (float) ((_gameTiming.CurTime - busy.StartedAt).TotalSeconds / duration.TotalSeconds);
        CastProgressBar.Visible = true;
        CastProgressBar.Value = Math.Clamp(fraction, 0f, 1f);
        var remaining = busy.EndsAt - _gameTiming.CurTime;
        CastProgressLabel.Text = remaining > TimeSpan.Zero
            ? $"{FormatStage(busy.Stage)}: {FormatDuration(remaining)} remaining"
            : $"{FormatStage(busy.Stage)}: completing";
    }

    private bool CanBeginSelectedLitany()
    {
        if (_snapshot is not { Active: true } snapshot || _selectedEntry is not { } entry)
            return false;
        if (!TryGetLitany(entry, out var litany))
            return false;
        if (!entry.Available
            || _busyState is not null
            || _choiceRequestId is not null
            || !string.IsNullOrWhiteSpace(snapshot.BusyReason))
            return false;
        if (!double.IsFinite(snapshot.Holiness) || !double.IsFinite(litany.Cost) || litany.Cost < 0)
            return false;

        return snapshot.Holiness + HolinessTolerance >= litany.Cost;
    }

    private void UpdateChoiceExpiryLabel()
    {
        var remaining = _choiceExpiresAt - _gameTiming.CurTime;
        ChoiceExpiryLabel.Text = remaining > TimeSpan.Zero
            ? $"Choice expires in: {FormatDuration(remaining)}"
            : "Choice expired.";
    }

    private bool ChoiceExpired()
    {
        return _choiceRequestId is not null && _gameTiming.CurTime >= _choiceExpiresAt;
    }

    private bool RequiresChoice(LitanyViewerEntry entry)
    {
        return TryGetLitany(entry, out var litany) && litany.TargetMode is not LitanyTargetMode.Self
            and not LitanyTargetMode.None;
    }

    private static bool CatalogChanged(List<LitanyViewerEntry> oldEntries, List<LitanyViewerEntry> newEntries)
    {
        if (oldEntries.Count != newEntries.Count)
            return true;

        foreach (var current in newEntries)
        {
            var previous = oldEntries.FirstOrDefault(entry => entry.Litany.Equals(current.Litany));
            if (previous is null || !EntryEqual(previous, current))
                return true;
        }

        return false;
    }

    private static bool EntryEqual(LitanyViewerEntry left, LitanyViewerEntry right)
    {
        return left.Litany.Equals(right.Litany)
               && left.Available == right.Available
               && left.UnavailableReason.Equals(right.UnavailableReason)
               && left.CooldownEndsAt == right.CooldownEndsAt;
    }

    private bool TryGetLitany(LitanyViewerEntry entry, out LitanyPrototype litany)
    {
        if (_prototypeManager.TryIndex(entry.Litany, out LitanyPrototype? prototype) && prototype != null)
        {
            litany = prototype;
            return true;
        }

        litany = null!;
        return false;
    }

    private string GetLitanyName(LitanyViewerEntry entry)
    {
        return TryGetLitany(entry, out var litany) ? Loc.GetString(litany.Name) : entry.Litany.ToString();
    }

    private string GetLitanyDescription(LitanyViewerEntry entry)
    {
        return TryGetLitany(entry, out var litany) ? Loc.GetString(litany.Description) : string.Empty;
    }

    private LitanyCategory GetLitanyCategory(LitanyViewerEntry entry)
    {
        return TryGetLitany(entry, out var litany) ? litany.Category : default;
    }

    private string GetAccessName(ProtoId<AccessLevelPrototype> accessId)
    {
        return _prototypeManager.TryIndex(accessId, out AccessLevelPrototype? access)
            ? access.GetAccessLevelName()
            : accessId.ToString();
    }

    private NeoTheologyProfilePrototype? GetProfile(ProtoId<NeoTheologyProfilePrototype>? profileId)
    {
        if (profileId is { } id &&
            _prototypeManager.TryIndex(id, out NeoTheologyProfilePrototype? profile) &&
            profile is not null)
        {
            return profile;
        }

        return null;
    }

    private static double GetMaximumHoliness(NeoTheologyProfilePrototype? profile)
    {
        var capacity = profile?.CruciformCapacity ?? 0d;
        return double.IsFinite(capacity) && capacity >= 0 ? capacity : 0d;
    }

    private void UpdatePlainTextCount()
    {
        var count = CountUnicodeScalars(PlainTextEdit.Text);
        PlainTextCountLabel.Text = $"Message length: {count}/{MaximumPlainTextScalars} Unicode scalars";
    }

    private static bool IsPlainTextLengthValid(string value)
    {
        return CountUnicodeScalars(value) <= MaximumPlainTextScalars;
    }

    private static int CountUnicodeScalars(string value)
    {
        return value.EnumerateRunes().Count();
    }

    private string GetBusyLitanyName(LitanyBusyState busy)
    {
        return _prototypeManager.TryIndex(busy.Litany, out LitanyPrototype? litany) && litany != null
            ? Loc.GetString(litany.Name)
            : busy.Litany.ToString();
    }

    private static string FormatStage(LitanyCastStage stage)
    {
        return stage switch
        {
            LitanyCastStage.Choosing => Loc.GetString("oxyd-litany-stage-choosing"),
            LitanyCastStage.Chanting => Loc.GetString("oxyd-litany-stage-chanting"),
            LitanyCastStage.ExtraDelay => Loc.GetString("oxyd-litany-stage-focusing"),
            LitanyCastStage.Committing => Loc.GetString("oxyd-litany-stage-completing"),
            _ => stage.ToString(),
        };
    }

    private static string FormatTargetMode(LitanyTargetMode mode)
    {
        return mode switch
        {
            LitanyTargetMode.Self => Loc.GetString("oxyd-litany-target-self"),
            LitanyTargetMode.AdjacentLiving => Loc.GetString("oxyd-litany-target-adjacent-living"),
            LitanyTargetMode.AdjacentFollower => Loc.GetString("oxyd-litany-target-adjacent-follower"),
            LitanyTargetMode.VisibleFollower => Loc.GetString("oxyd-litany-target-visible-follower"),
            LitanyTargetMode.StationFollower => Loc.GetString("oxyd-litany-target-station-follower"),
            LitanyTargetMode.FrontMachine => Loc.GetString("oxyd-litany-target-front-machine"),
            LitanyTargetMode.NearbyMachine => Loc.GetString("oxyd-litany-target-nearby-machine"),
            LitanyTargetMode.VisibleArea => Loc.GetString("oxyd-litany-target-visible-area"),
            LitanyTargetMode.FrontTile => Loc.GetString("oxyd-litany-target-front-tile"),
            LitanyTargetMode.Ceremony => Loc.GetString("oxyd-litany-target-ceremony"),
            LitanyTargetMode.GlobalFollower => Loc.GetString("oxyd-litany-target-global-follower"),
            _ => Loc.GetString("oxyd-litany-target-none"),
        };
    }

    private static string FormatDuration(TimeSpan duration)
    {
        if (duration <= TimeSpan.Zero)
            return "none";
        if (duration.TotalHours >= 1)
            return $"{duration.TotalHours:0.##} h";
        if (duration.TotalMinutes >= 1)
            return $"{duration.TotalMinutes:0.##} min";
        return $"{duration.TotalSeconds:0.##} s";
    }
}
