using Content.Client.UserInterface.Screens;

namespace Content.Client._Oxyd.UI;

using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


[GenerateTypedNameReferences]
public sealed partial class ErisUIGameScreen : InGameScreen
{
    public const string StyleClassChatContainer = "ChatContainer";
    public const string StyleClassChatOutput = "ChatOutput";

    public ErisUIGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);
        
    }

    private void ResizeActionContainer()
    {
        Actions.ActionsContainer.MaxGridWidth = LeftSplit.MinWidth;
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        //ScreenContainer.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
    }
}
