using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Components;
using Content.Shared.FixedPoint;
using Content.Shared.Medical.Cryogenics;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Content.Shared.Damage.Systems;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris cryo cell NanoUI (cryo.tmpl): "Cryo Cell Status" box showing the occupant
/// name + Conscious/Unconscious/DEAD coloring with health &amp; damage bars and the
/// "Cell Temperature" line, the On/Off link pair, "Eject Occupant", the inject
/// pills and the beaker contents box with an Eject link.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydCryoPodWindow : FancyWindow
{
    public event Action? OnEjectPatientPressed;
    public event Action? OnEjectBeakerPressed;
    public event Action<FixedPoint2>? OnInjectPressed;
    public event Action<bool>? OnPowerPressed;

    private bool _optimisticOn = true;
    private bool _haveOptimistic;

    public OxydCryoPodWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));
    }

    public void Populate(CryoPodUserMessage message, EntityUid owner, IEntityManager entMan)
    {
        var on = entMan.System<AppearanceSystem>()
            .TryGetData<bool>(owner, CryoPodVisuals.IsOn, out var isOn) && isOn;
        if (_haveOptimistic && on == _optimisticOn)
            _haveOptimistic = false; // server caught up with our optimistic flip
        var showOn = _haveOptimistic ? _optimisticOn : on;

        Content.RemoveAllChildren();

        // ---- Cryo Cell Status box ----
        var statusBox = new ErisStatusBox { HorizontalExpand = true };
        var statusCol = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 4,
        };
        statusBox.AddChild(statusCol);
        statusCol.AddChild(new ErisItemLabel(Loc.GetString("oxyd-cryo-status-title")));

        var patient = message.Health.TargetEntity is { } net
            ? entMan.GetEntity(net)
            : (EntityUid?) null;
        if (patient is { } p)
        {
            var mobState = entMan.TryGetComponent<MobStateComponent>(p, out var mobStateComp)
                ? mobStateComp.CurrentState
                : MobState.Invalid;
            var dead = mobState == MobState.Dead
                       || message.Health.Unrevivable == true;
            var (stateText, stateColor) = dead
                ? (Loc.GetString("oxyd-cryo-dead"), ErisSurgeryColors.BadText)
                : mobState == MobState.Alive
                    ? (Loc.GetString("oxyd-cryo-conscious"), ErisSurgeryColors.GoodText)
                    : (Loc.GetString("oxyd-cryo-unconscious"), ErisSurgeryColors.BarAverage);

            var nameRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 6,
            };
            nameRow.AddChild(new Label
            {
                Text = entMan.GetComponent<MetaDataComponent>(p).EntityName,
                FontColorOverride = ErisSurgeryColors.Text,
                HorizontalExpand = true,
            });
            nameRow.AddChild(new Label { Text = stateText, FontColorOverride = stateColor });
            statusCol.AddChild(nameRow);

            // Health bar (percent of critical threshold remaining) + total damage.
            var damage = entMan.TryGetComponent<DamageableComponent>(p, out _)
                ? entMan.System<DamageableSystem>().GetTotalDamage(p).Float()
                : 0f;
            var healthFrac = Math.Clamp(1f - damage / 200f, 0f, 1f);
            var bar = new ErisBar { HorizontalExpand = true };
            bar.SetValue(healthFrac, healthFrac > 0.5f
                    ? ErisSurgeryColors.BarGood
                    : healthFrac > 0.25f
                        ? ErisSurgeryColors.BarAverage
                        : ErisSurgeryColors.BarBad,
                $"{(int) damage} dmg");
            statusCol.AddChild(bar);
        }
        else
        {
            statusCol.AddChild(new ErisSubLabel(Loc.GetString("oxyd-sleeper-empty")));
        }

        // Cell temperature (gas mix Kelvin -> Celsius like the Eris readout).
        var celsius = message.GasMix.Temperature - 273.15f;
        var tempRow = new ErisSpecRow(Loc.GetString("oxyd-cryo-cell-temp"), 130f);
        tempRow.AddValue(new Label
        {
            Text = $"{celsius:0.0}°C",
            FontColorOverride = celsius < -20f
                ? Color.FromHex("#0080ff")
                : ErisSurgeryColors.Text,
        });
        statusCol.AddChild(tempRow);
        Content.AddChild(statusBox);

        // ---- On / Off + Eject Occupant ----
        var controls = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
        };
        var onLink = new ErisLink(Loc.GetString("oxyd-processor-on"));
        var offLink = new ErisLink(Loc.GetString("oxyd-processor-off"));
        if (showOn)
        {
            onLink.SetSelectedLook();
            offLink.SetUnselectedLook();
        }
        else
        {
            onLink.SetUnselectedLook();
            offLink.SetSelectedLook();
        }
        onLink.OnPressed += _ =>
        {
            _optimisticOn = true;
            _haveOptimistic = true;
            OnPowerPressed?.Invoke(true);
            onLink.SetSelectedLook();
            offLink.SetUnselectedLook();
        };
        offLink.OnPressed += _ =>
        {
            _optimisticOn = false;
            _haveOptimistic = true;
            OnPowerPressed?.Invoke(false);
            onLink.SetUnselectedLook();
            offLink.SetSelectedLook();
        };
        controls.AddChild(onLink);
        controls.AddChild(offLink);

        controls.AddChild(new Control { HorizontalExpand = true });
        var eject = new ErisLink(Loc.GetString("oxyd-sleeper-eject-occupant"));
        eject.OnPressed += _ => OnEjectPatientPressed?.Invoke();
        if (patient == null)
            eject.SetDisabledLook();
        controls.AddChild(eject);
        Content.AddChild(controls);

        // ---- Inject pills (stock function kept, Eris pill look) ----
        var injectRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
        };
        injectRow.AddChild(new ErisSubLabel(Loc.GetString("oxyd-dispenser-dispense")));
        foreach (var amount in new FixedPoint2[] { 1, 5, 10, 20 })
        {
            var a = amount;
            var link = new ErisLink($"{(int) a}");
            link.OnPressed += _ => OnInjectPressed?.Invoke(a);
            injectRow.AddChild(link);
        }
        Content.AddChild(injectRow);

        // ---- Beaker contents statusDisplay + Eject ----
        var beakerBox = new ErisStatusBox { HorizontalExpand = true, VerticalExpand = true };
        var beakerCol = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 2,
        };
        beakerBox.AddChild(beakerCol);
        beakerCol.AddChild(new ErisItemLabel(Loc.GetString("oxyd-dispenser-beaker-contents")));
        if (message.Beaker is { Count: > 0 })
        {
            var protos = IoCManager.Resolve<IPrototypeManager>();
            foreach (var reagent in message.Beaker)
            {
                beakerCol.AddChild(new Label
                {
                    Text = protos.TryIndex<ReagentPrototype>(
                               reagent.Reagent.Prototype, out var proto)
                        ? $"{proto.LocalizedName} ({reagent.Quantity}u)"
                        : $"{reagent.Reagent.Prototype} ({reagent.Quantity}u)",
                    FontColorOverride = ErisSurgeryColors.Text,
                });
            }
        }
        else
        {
            beakerCol.AddChild(new ErisSubLabel(Loc.GetString("oxyd-cryo-no-beaker")));
        }
        var ejectBeakerRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
        };
        var ejectBeaker = new ErisLink(Loc.GetString("oxyd-cryo-eject-beaker"));
        ejectBeaker.OnPressed += _ => OnEjectBeakerPressed?.Invoke();
        if (message.Beaker == null)
            ejectBeaker.SetDisabledLook();
        ejectBeakerRow.AddChild(ejectBeaker);
        beakerCol.AddChild(ejectBeakerRow);
        Content.AddChild(beakerBox);
    }
}
