using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>Eris surgery_organ.tmpl port: organ cards on the left, the selected organ's
/// diagnostics / cavity volume / conditions on the right. Built entirely from stock controls.</summary>
[GenerateTypedNameReferences]
public sealed partial class OxydSurgeryWindow : FancyWindow
{
    private static readonly Color WoundRed = Color.FromHex("#a0222a");

    private OxydSurgeryState? _state;
    private NetEntity? _selectedOrgan;

    public event Action<NetEntity, OxydSurgeryStep>? StepSelected;

    public OxydSurgeryWindow()
    {
        RobustXamlLoader.Load(this);

        DiagnoseButton.OnPressed += _ => SelectStep(OxydSurgeryStep.DiagnoseWound);
        ShrapnelButton.OnPressed += _ => SelectStep(OxydSurgeryStep.RemoveEmbedded);
    }

    private void SelectStep(OxydSurgeryStep step)
    {
        if (_selectedOrgan is { } sel)
            StepSelected?.Invoke(sel, step);
    }

    public void UpdateState(OxydSurgeryState state)
    {
        _state = state;
        PatientLabel.Text = Loc.GetString("oxyd-surgery-patient", ("patient", state.PatientName));
        ToolLabel.Text = Loc.GetString("oxyd-surgery-held-tools",
            ("tool", string.IsNullOrEmpty(state.HeldItemName)
                ? Loc.GetString("oxyd-surgery-no-tool")
                : state.HeldItemName));

        // Keep the selection across state pushes; fall back to the first organ like Eris's view.
        if (_selectedOrgan is not { } cur || state.Organs.All(o => o.Organ != cur))
            _selectedOrgan = state.Organs.FirstOrDefault()?.Organ;

        OrganCards.RemoveAllChildren();
        foreach (var organ in state.Organs)
            OrganCards.AddChild(BuildOrganCard(organ));

        RebuildDetail();
    }

    /// <summary>Eris organ card: header (red underline when a fleshy organ is open/wounded),
    /// icon, Mods/Wounds link, diagnosed wound info, condition fixes and step links.</summary>
    private Control BuildOrganCard(OxydSurgeryOrganEntry organ)
    {
        var card = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 3 };

        var wounded = organ.Incision != OxydIncisionStage.None || organ.OrganDamage > 0 || organ.Fractured;
        card.AddChild(new Label { Text = organ.Name, StyleClasses = { StyleClass.LabelSubHeading } });
        if (!organ.Robotic && wounded)
        {
            card.AddChild(new PanelContainer
            {
                MinHeight = 2,
                PanelOverride = new StyleBoxFlat(WoundRed),
            });
        }

        var headRow = new BoxContainer { SeparationOverride = 6 };
        var sprite = new SpriteView { SetSize = new Vector2(32, 32), OverrideDirection = Direction.South };
        sprite.SetEntity(organ.Organ);
        headRow.AddChild(sprite);
        var modsButton = new Button
        {
            Text = Loc.GetString("oxyd-surgery-mods-wounds"),
            StyleClasses = { StyleClass.ButtonSmall },
            HorizontalAlignment = HAlignment.Right,
            HorizontalExpand = true,
        };
        var organNet = organ.Organ;
        modsButton.OnPressed += _ =>
        {
            _selectedOrgan = organNet;
            RebuildDetail();
        };
        headRow.AddChild(modsButton);
        card.AddChild(headRow);

        if (organ.RunningStep is { } running)
            card.AddChild(new Label { Text = $"{Loc.GetString($"oxyd-surgery-step-{running.ToString().ToLowerInvariant()}")}…", StyleClasses = { StyleClass.LabelWeak } });

        if (!organ.Diagnosed)
        {
            card.AddChild(new Label { Text = Loc.GetString("oxyd-surgery-undiagnosed"), StyleClasses = { StyleClass.LabelWeak } });
        }
        else
        {
            var wounds = ConditionCount(organ);
            if (wounds > 0)
                AddLabelRow(card, Loc.GetString("oxyd-surgery-wounds"), wounds.ToString());

            if (organ.MaxDamage > 0)
                AddBarRow(card, Loc.GetString("oxyd-surgery-health"), (organ.MaxDamage - organ.OrganDamage) / organ.MaxDamage);

            var status = string.Join(", ", StatusMarkers(organ));
            if (status.Length > 0)
                card.AddChild(new Label { Text = status, StyleClasses = { StyleClass.LabelSubText } });
        }

        AddConditionRows(card, organ);

        foreach (var step in organ.AvailableSteps)
        {
            var localStep = step;
            var button = new Button { Text = Loc.GetString($"oxyd-surgery-step-{step.ToString().ToLowerInvariant()}") };
            button.OnPressed += _ => StepSelected?.Invoke(organNet, localStep);
            card.AddChild(button);
        }

        return new PanelContainer { StyleClasses = { StyleClass.BackgroundPanelDark }, Children = { card }, Margin = new Thickness(6) };
    }

    /// <summary>Condition -> fixing step (Eris conditions' fix_name links).</summary>
    private static List<(string Name, OxydSurgeryStep Fix)> ConditionsFor(OxydSurgeryOrganEntry organ)
    {
        var list = new List<(string, OxydSurgeryStep)>();
        if (organ is { Incision: not OxydIncisionStage.None, Clamped: false })
            list.Add((Loc.GetString("oxyd-surgery-cond-bleeding"), OxydSurgeryStep.FixBleeding));
        if (organ.Fractured)
            list.Add((Loc.GetString("oxyd-surgery-cond-fracture"), OxydSurgeryStep.MendBone));
        if (organ.EmbeddedCount > 0)
            list.Add((Loc.GetString("oxyd-surgery-cond-embedded"), OxydSurgeryStep.RemoveEmbedded));
        if (organ.OrganDamage > 0)
            list.Add((Loc.GetString("oxyd-surgery-cond-damage"), OxydSurgeryStep.FixOrgan));
        if (organ.Robotic && organ.OrganDamage > 0)
            list.Add((Loc.GetString("oxyd-surgery-cond-robo"), OxydSurgeryStep.RoboFixBrute));
        return list;
    }

    private static int ConditionCount(OxydSurgeryOrganEntry organ)
    {
        var n = 0;
        if (organ is { Incision: not OxydIncisionStage.None, Clamped: false }) n++;
        if (organ.Fractured) n++;
        if (organ.EmbeddedCount > 0) n++;
        if (organ.OrganDamage > 0) n++;
        return n;
    }

    private static List<string> StatusMarkers(OxydSurgeryOrganEntry organ)
    {
        var markers = new List<string>();
        if (organ.Incision != OxydIncisionStage.None)
            markers.Add(organ.Incision == OxydIncisionStage.Retracted ? "retracted" : "open");
        if (organ is { Incision: not OxydIncisionStage.None, Clamped: false })
            markers.Add("bleeding");
        if (organ.Fractured)
            markers.Add("fractured");
        if (organ.Splinted)
            markers.Add("splinted");
        if (organ.Robotic)
            markers.Add("robotic");
        if (!organ.External)
            markers.Add("internal");
        return markers;
    }

    /// <summary>"Condition: [Fix]" rows like Eris's condition links; fixes disable when
    /// the held tool can't run that step (Eris organ.open gating).</summary>
    private void AddConditionRows(BoxContainer parent, OxydSurgeryOrganEntry organ)
    {
        foreach (var (name, fix) in ConditionsFor(organ))
        {
            var row = new BoxContainer { SeparationOverride = 6 };
            row.AddChild(new Label { Text = $"{name}:", StyleClasses = { StyleClass.LabelKeyText } });
            var fixButton = new Button
            {
                Text = Loc.GetString($"oxyd-surgery-step-{fix.ToString().ToLowerInvariant()}"),
                HorizontalAlignment = HAlignment.Right,
                HorizontalExpand = true,
                Disabled = !organ.AvailableSteps.Contains(fix),
            };
            var organNet = organ.Organ;
            fixButton.OnPressed += _ => StepSelected?.Invoke(organNet, fix);
            row.AddChild(fixButton);
            parent.AddChild(row);
        }
    }

    private void AddLabelRow(BoxContainer parent, string label, string value)
    {
        var row = new BoxContainer { SeparationOverride = 6 };
        row.AddChild(new Label { Text = $"{label}:", StyleClasses = { StyleClass.LabelKeyText } });
        row.AddChild(new Label { Text = value });
        parent.AddChild(row);
    }

    private void AddBarRow(BoxContainer parent, string label, float fraction)
    {
        var row = new BoxContainer { SeparationOverride = 6 };
        row.AddChild(new Label { Text = $"{label}:", StyleClasses = { StyleClass.LabelKeyText } });
        row.AddChild(new ProgressBar { MinValue = 0, MaxValue = 1, Value = Math.Clamp(fraction, 0f, 1f), HorizontalExpand = true });
        parent.AddChild(row);
    }

    /// <summary>Right pane (Eris's Diagnostics / Volume / Conditions cards for the selected organ).</summary>
    private void RebuildDetail()
    {
        ConditionRows.RemoveAllChildren();
        var organ = _state?.Organs.FirstOrDefault(o => o.Organ == _selectedOrgan);
        if (_state == null || organ == null)
        {
            DiagOrganLabel.Text = Loc.GetString("oxyd-surgery-select-organ");
            DiagHealthBar.Value = 0;
            DiagStatusLabel.Text = "";
            DiagEffLabel.Text = "";
            VolumeLabel.Text = "";
            DiagnoseButton.Visible = false;
            ShrapnelButton.Visible = false;
            return;
        }

        DiagOrganLabel.Text = organ.Name;
        DiagHealthBar.Value = organ.MaxDamage > 0
            ? Math.Clamp((organ.MaxDamage - organ.OrganDamage) / organ.MaxDamage, 0f, 1f)
            : 0f;

        if (!organ.Diagnosed)
        {
            DiagStatusLabel.Text = Loc.GetString("oxyd-surgery-undiagnosed");
            DiagEffLabel.Text = "";
        }
        else
        {
            DiagStatusLabel.Text = string.Join(", ", StatusMarkers(organ));
            DiagEffLabel.Text = Loc.GetString("oxyd-surgery-efficiency",
                ("pct", (int) Math.Max(0, 100 - organ.OrganDamage)));
        }

        DiagnoseButton.Visible = !organ.Diagnosed;

        VolumeLabel.Text = Loc.GetString("oxyd-surgery-occupied",
            ("cur", organ.EmbeddedCount), ("max", organ.CavityMax));
        ShrapnelButton.Visible = organ.EmbeddedCount > 0;
        ShrapnelButton.Disabled = !organ.AvailableSteps.Contains(OxydSurgeryStep.RemoveEmbedded);

        if (organ.Diagnosed)
            AddConditionRows(ConditionRows, organ);
        else
            ConditionRows.AddChild(new Label { Text = Loc.GetString("oxyd-surgery-undiagnosed"), StyleClasses = { StyleClass.LabelWeak } });
    }
}
