using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Storage;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris chemical dispenser NanoUI (chem_dispenser.tmpl): the Dispense amount
/// pills (5/10/20/30/40), the chemical link grid (one blue pill per reagent,
/// colored by substance), then the "Beaker Contents" statusDisplay with its
/// reagent list and an Eject link.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydReagentDispenserWindow : FancyWindow
{
    public event Action<ReagentDispenserDispenseAmount>? OnDispenseAmountPressed;
    public event Action<ItemStorageLocation>? OnDispenseReagentPressed;
    public event Action? OnEjectBeakerPressed;

    // Eris dispense amounts (subset of the stock enum).
    private static readonly ReagentDispenserDispenseAmount[] Amounts =
    {
        ReagentDispenserDispenseAmount.U5,
        ReagentDispenserDispenseAmount.U10,
        ReagentDispenserDispenseAmount.U20,
        ReagentDispenserDispenseAmount.U30,
        ReagentDispenserDispenseAmount.U40,
    };

    public OxydReagentDispenserWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));
    }

    public void UpdateState(ReagentDispenserBoundUserInterfaceState state)
    {
        Content.RemoveAllChildren();

        // ---- Dispense amount pills ----
        var amountRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };
        amountRow.AddChild(new ErisItemLabel(Loc.GetString("oxyd-dispenser-dispense")));
        foreach (var amount in Amounts)
        {
            var a = amount;
            var pill = new ErisLink(((int) a).ToString());
            if (a == state.SelectedDispenseAmount)
                pill.SetSelectedLook();
            else
                pill.SetUnselectedLook();
            pill.OnPressed += _ => OnDispenseAmountPressed?.Invoke(a);
            amountRow.AddChild(pill);
        }
        Content.AddChild(amountRow);

        // ---- Chemical link grid ----
        Content.AddChild(new ErisItemLabel(Loc.GetString("oxyd-dispenser-chemicals")));
        var chemScroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        var chemGrid = new GridContainer
        {
            Columns = 2,
            HorizontalExpand = true,
            VSeparationOverride = 4,
            HSeparationOverride = 6,
        };
        chemScroll.AddChild(chemGrid);
        foreach (var item in state.Inventory)
        {
            var location = item.StorageLocation;
            var link = new ErisLink(item.ReagentLabel) { HorizontalExpand = true };
            link.OnPressed += _ => OnDispenseReagentPressed?.Invoke(location);
            chemGrid.AddChild(link);
        }
        Content.AddChild(chemScroll);

        // ---- Beaker Contents statusDisplay + Eject ----
        var beakerBox = new ErisStatusBox { HorizontalExpand = true };
        var beakerCol = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 2,
        };
        beakerBox.AddChild(beakerCol);
        beakerCol.AddChild(new ErisItemLabel(Loc.GetString("oxyd-dispenser-beaker-contents")));

        var hasBeaker = state.OutputContainer != null;
        if (state.OutputContainer?.Reagents is { Count: > 0 } reagents)
        {
            var protos = IoCManager.Resolve<IPrototypeManager>();
            foreach (var reagent in reagents)
            {
                beakerCol.AddChild(new Label
                {
                    Text = protos.TryIndex<ReagentPrototype>(
                               reagent.Reagent.Prototype, out var proto)
                        ? $"{proto.LocalizedName} ({reagent.Quantity}u)"
                        : $"{reagent.Reagent.Prototype} ({reagent.Quantity}u)",
                    FontColorOverride = ErisSurgeryColors.Text,
                });
            }
        }
        else
        {
            beakerCol.AddChild(new ErisSubLabel(Loc.GetString("oxyd-dispenser-empty")));
        }

        var ejectRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
        };
        var eject = new ErisLink(Loc.GetString("oxyd-processor-eject"));
        eject.OnPressed += _ => OnEjectBeakerPressed?.Invoke();
        if (!hasBeaker)
            eject.SetDisabledLook();
        ejectRow.AddChild(eject);
        beakerCol.AddChild(ejectRow);
        Content.AddChild(beakerBox);
    }
}
