using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris operating computer readout (machinery/computer/Operating.dm): patient name,
/// Stable/Non-Responsive status, Critical Health + Organ Health percentages, one
/// displayBar per damage group, blood level, and the heartbeat/pulse line.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydOpVitalsWindow : FancyWindow
{
    public OxydOpVitalsWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));
    }

    private static Color BarColor(float damage) => damage switch
    {
        > 50f => ErisSurgeryColors.BarBad,
        > 25f => ErisSurgeryColors.BarAverage,
        _ => ErisSurgeryColors.BarGood,
    };

    public void UpdateState(OxydOperatingComputerState state)
    {
        Rows.RemoveAllChildren();

        var header = new ErisItemLabel(Loc.GetString("oxyd-opcomputer-patient-info"));
        Rows.AddChild(header);

        if (!state.HasPatient)
        {
            var empty = new ErisStatusBox();
            empty.AddChild(new ErisSubLabel(Loc.GetString("oxyd-opcomputer-no-patient")));
            Rows.AddChild(empty);
            return;
        }

        var card = new ErisPanel();
        var cardBox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 4,
            HorizontalExpand = true,
        };
        card.AddChild(cardBox);
        Rows.AddChild(card);

        var nameRow = new ErisSpecRow(Loc.GetString("oxyd-opcomputer-name"));
        nameRow.AddValue(new Label { Text = state.PatientName, FontColorOverride = ErisSurgeryColors.Text });
        cardBox.AddChild(nameRow);

        // Eris "Patient Status": Non-Responsive when unconscious/dead, Stable otherwise.
        var statusRow = new ErisSpecRow(Loc.GetString("oxyd-opcomputer-status"));
        var (statusText, statusColor) = !state.Alive
            ? (Loc.GetString("oxyd-opcomputer-status-dead"), ErisSurgeryColors.BadText)
            : state.Critical
                ? (Loc.GetString("oxyd-opcomputer-status-crit"), ErisSurgeryColors.BarAverage)
                : (Loc.GetString("oxyd-opcomputer-status-stable"), ErisSurgeryColors.GoodText);
        statusRow.AddValue(new Label { Text = statusText, FontColorOverride = statusColor });
        cardBox.AddChild(statusRow);

        var critRow = new ErisSpecRow(Loc.GetString("oxyd-opcomputer-crit-health"));
        critRow.AddValue(new Label
        {
            Text = $"{(int) state.HealthPercent}%",
            FontColorOverride = BarColor(100f - state.HealthPercent),
        });
        cardBox.AddChild(critRow);

        var organRow = new ErisSpecRow(Loc.GetString("oxyd-opcomputer-organ-health"));
        organRow.AddValue(new Label
        {
            Text = $"{(int) state.OrganHealth}%",
            FontColorOverride = BarColor(100f - state.OrganHealth),
        });
        cardBox.AddChild(organRow);

        if (state.HasBlood)
        {
            var bloodRow = new ErisSpecRow(Loc.GetString("oxyd-opcomputer-blood"));
            bloodRow.AddValue(new Label
            {
                Text = Loc.GetString("oxyd-opcomputer-blood-value",
                    ("pct", (int) state.BloodPercent), ("units", (int) state.BloodVolume)),
                FontColorOverride = state.BloodPercent < 60f
                    ? ErisSurgeryColors.BadText
                    : ErisSurgeryColors.Text,
            });
            cardBox.AddChild(bloodRow);
        }

        // Eris "Heartbeat rate" (get_pulse classification).
        var pulseRow = new ErisSpecRow(Loc.GetString("oxyd-opcomputer-pulse"));
        var (pulseKey, pulseColor) = state.Pulse switch
        {
            OxydPulse.None => ("oxyd-pulse-none", ErisSurgeryColors.BadText),
            OxydPulse.Thready => ("oxyd-pulse-thready", ErisSurgeryColors.BarAverage),
            OxydPulse.Irregular => ("oxyd-pulse-irregular", ErisSurgeryColors.BarAverage),
            _ => ("oxyd-pulse-norm", ErisSurgeryColors.GoodText),
        };
        pulseRow.AddValue(new Label { Text = Loc.GetString(pulseKey), FontColorOverride = pulseColor });
        cardBox.AddChild(pulseRow);

        // Damage displayBars in a 2x2 grid like the sleeper/surgery screens.
        var bars = new GridContainer { Columns = 2, HorizontalExpand = true, VSeparationOverride = 4 };
        AddBar(bars, Loc.GetString("oxyd-opcomputer-bar-brute"), state.BruteLoss);
        AddBar(bars, Loc.GetString("oxyd-opcomputer-bar-burn"), state.BurnLoss);
        AddBar(bars, Loc.GetString("oxyd-opcomputer-bar-toxin"), state.ToxinLoss);
        AddBar(bars, Loc.GetString("oxyd-opcomputer-bar-asphyx"), state.OxyLoss);
        Rows.AddChild(bars);
    }

    private static void AddBar(GridContainer grid, string name, float damage)
    {
        var box = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        var label = new ErisSubLabel(name);
        label.SetWidth = 90f;
        box.AddChild(label);
        var bar = new ErisBar();
        bar.HorizontalExpand = true;
        bar.MinWidth = 110f;
        bar.SetValue(Math.Clamp(damage / 100f, 0f, 1f), BarColor(damage),
            $"{(int) Math.Max(0f, damage)}");
        box.AddChild(bar);
        grid.AddChild(box);
    }
}
