using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>Eris autodoc_capitalism.tmpl: balance header, Scan/Process/Abort row, progress bar,
/// then per-patchnote cards with costed operation toggles.</summary>
[GenerateTypedNameReferences]
public sealed partial class OxydAutodocWindow : FancyWindow
{
    public event Action? ScanRequested;
    public event Action? ProcessAllRequested;
    public event Action? ProcessPickedRequested;
    public event Action? AbortRequested;
    public event Action? EjectRequested;
    public event Action? EjectCreditsRequested;
    public event Action<int, OxydAutodocOp>? ToggleRequested;

    public OxydAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        ScanButton.OnPressed += _ => ScanRequested?.Invoke();
        ProcessAllButton.OnPressed += _ => ProcessAllRequested?.Invoke();
        ProcessPickedButton.OnPressed += _ => ProcessPickedRequested?.Invoke();
        AbortButton.OnPressed += _ => AbortRequested?.Invoke();
        EjectButton.OnPressed += _ => EjectRequested?.Invoke();
        EjectCreditsButton.OnPressed += _ => EjectCreditsRequested?.Invoke();
    }

    private static string OpName(OxydAutodocOp op) => Loc.GetString($"oxyd-autodoc-op-{op.ToString().ToLowerInvariant()}");

    public void UpdateState(OxydAutodocState state)
    {
        BalanceLabel.Text = Loc.GetString("oxyd-autodoc-balance", ("balance", state.Balance));
        ScanButton.Text = Loc.GetString("oxyd-autodoc-scan", ("cost", state.ScanCost));
        ProcessAllButton.Text = Loc.GetString("oxyd-autodoc-process-all", ("cost", state.TotalCost));
        ProcessPickedButton.Text = Loc.GetString("oxyd-autodoc-process-picked", ("cost", state.CustomCost));

        var hasOccupant = state.HasOccupant;
        var hasNotes = state.Organs.Count > 0 || state.Global.Available.Count > 0;
        ScanButton.Disabled = state.Running || !hasOccupant;
        ProcessAllButton.Disabled = state.Running || !hasOccupant || !hasNotes;
        ProcessPickedButton.Disabled = state.Running || !hasOccupant || !hasNotes || state.CustomCost <= 0;
        AbortButton.Disabled = !state.Running;
        EjectButton.Disabled = state.Running;
        EjectCreditsButton.Disabled = state.Running || state.Balance <= 0;

        RunningLabel.Text = state.Running ? Loc.GetString("oxyd-autodoc-in-progress") : "";
        ProgressBar.Visible = state.Running;
        ProgressBar.Value = state.Progress * 100f;

        EntriesBox.RemoveAllChildren();

        if (!hasOccupant)
        {
            EntriesBox.AddChild(new Label { Text = Loc.GetString("oxyd-autodoc-empty") });
            return;
        }

        if (!hasNotes)
        {
            EntriesBox.AddChild(new Label { Text = Loc.GetString("oxyd-autodoc-no-scan") });
            return;
        }

        // Overall status card (Eris toxnote: bars + global ops).
        var global = state.Global;
        var gcard = new PanelContainer { StyleClasses = { "BorderedWindowPanel" } };
        var gv = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4, Margin = new Thickness(6) };
        gv.AddChild(new Label { Text = Loc.GetString("oxyd-autodoc-overall"), StyleClasses = { "LabelHeading" } });
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-brute"), state.BruteLoss, 100f, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-burn"), state.BurnLoss, 100f, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-toxin"), state.ToxinLoss, 100f, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-oxy"), state.OxyLoss, 100f, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-blood-level"), state.BloodPercent, 100f, invert: false));
        AddOpButtons(gv, global, state, running: state.Running);
        gcard.AddChild(gv);
        EntriesBox.AddChild(gcard);

        // Per-organ cards.
        foreach (var organ in state.Organs)
        {
            var card = new PanelContainer { StyleClasses = { "BorderedWindowPanel" } };
            var v = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4, Margin = new Thickness(6) };
            v.AddChild(new Label { Text = organ.Name, StyleClasses = { "LabelHeading" } });
            var damage = organ.Internal
                ? Loc.GetString("oxyd-autodoc-inner-damage", ("dmg", (int) organ.InnerDamage))
                : Loc.GetString("oxyd-autodoc-organ-damage",
                    ("brute", (int) organ.BruteDamage), ("burn", (int) organ.BurnDamage));
            v.AddChild(new Label { Text = damage });
            AddOpButtons(v, organ, state, running: state.Running);
            card.AddChild(v);
            EntriesBox.AddChild(card);
        }
    }

    private void AddOpButtons(BoxContainer box, OxydAutodocEntry entry, OxydAutodocState state, bool running)
    {
        foreach (var op in entry.Available)
        {
            var picked = entry.Picked.Contains(op);
            var cost = state.OpCosts.GetValueOrDefault(op);
            var id = entry.Id;
            var btn = new Button
            {
                Text = Loc.GetString("oxyd-autodoc-op-cost",
                    ("op", OpName(op)), ("cost", cost)) + (picked ? " ✓" : ""),
                Disabled = running || !entry.Available.Contains(op),
            };
            btn.OnPressed += _ => ToggleRequested?.Invoke(id, op);
            box.AddChild(btn);
        }
    }

    private static Control Bar(string name, float value, float max, bool invert)
    {
        var row = new BoxContainer { SeparationOverride = 6 };
        var label = new Label { Text = name };
        label.SetWidth = 140;
        label.ClipText = true;
        row.AddChild(label);
        var bar = new ProgressBar
        {
            MinValue = 0,
            MaxValue = max,
            Value = invert ? max - Math.Clamp(value, 0, max) : Math.Clamp(value, 0, max),
            HorizontalExpand = true,
        };
        row.AddChild(bar);
        var num = new Label { Text = ((int) value).ToString() };
        row.AddChild(num);
        return row;
    }
}
