using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class OxydChemProcessorWindow : FancyWindow
{
    public event Action<string, int>? TargetSet;
    public event Action? StartRequested;
    public event Action<int>? EjectRequested;

    public OxydChemProcessorWindow()
    {
        RobustXamlLoader.Load(this);
        StartButton.OnPressed += _ => StartRequested?.Invoke();
        EjectMainButton.OnPressed += _ => EjectRequested?.Invoke(-1);
    }

    public void UpdateState(OxydChemProcessorState state)
    {
        ModeLabel.Text = state.Mode == OxydChemProcessorMode.Centrifuge
            ? Loc.GetString("oxyd-processor-mode-centrifuge")
            : Loc.GetString("oxyd-processor-mode-electrolyzer");

        MainContents.RemoveAllChildren();
        if (!state.HasMainBeaker)
        {
            MainContents.AddChild(new Label { Text = Loc.GetString("oxyd-processor-no-beaker") });
        }
        else
        {
            foreach (var reagent in state.MainContents)
            {
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
                row.AddChild(new Label { Text = $"{reagent.Name} ({reagent.Volume:0.#}u)", HorizontalExpand = true });
                if (state.Mode == OxydChemProcessorMode.Centrifuge)
                {
                    var option = new OptionButton();
                    for (var i = -1; i < OxydChemProcessorComponent.SeparationBeakerCount; i++)
                    {
                        var label = i < 0
                            ? Loc.GetString("oxyd-processor-leave")
                            : Loc.GetString("oxyd-processor-beaker-n", ("n", i + 1));
                        option.AddItem(label, i + 1);
                    }
                    option.TrySelectId(reagent.TargetBeaker + 1);
                    var id = reagent.Id;
                    option.OnItemSelected += args => TargetSet?.Invoke(id, args.Id - 1);
                    row.AddChild(option);
                }
                MainContents.AddChild(row);
            }
        }

        SepBeakers.RemoveAllChildren();
        for (var i = 0; i < state.SeparationBeakers.Count; i++)
        {
            var beaker = state.SeparationBeakers[i];
            var index = i;
            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };
            box.AddChild(new Label
            {
                Text = beaker.Present
                    ? Loc.GetString("oxyd-processor-beaker-status", ("n", i + 1), ("vol", (int) beaker.Volume))
                    : Loc.GetString("oxyd-processor-beaker-empty", ("n", i + 1)),
            });
            foreach (var content in beaker.Contents)
                box.AddChild(new Label { Text = $"  {content.Name} ({content.Volume:0.#}u)" });
            var eject = new Button { Text = Loc.GetString("oxyd-processor-eject"), Disabled = !beaker.Present };
            eject.OnPressed += _ => EjectRequested?.Invoke(index);
            box.AddChild(eject);
            SepBeakers.AddChild(box);
        }

        StartButton.Disabled = state.Working || !state.HasMainBeaker;
        EjectMainButton.Disabled = state.Working || !state.HasMainBeaker;
    }
}
