using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class OxydSurgeryWindow : FancyWindow
{
    private OxydSurgeryState? _state;
    private NetEntity? _selectedOrgan;

    public event Action<NetEntity, OxydSurgeryStep>? StepSelected;

    public OxydSurgeryWindow()
    {
        RobustXamlLoader.Load(this);

        OrganList.OnItemSelected += args =>
        {
            _selectedOrgan = OrganList[args.ItemIndex].Metadata is NetEntity ent ? ent : null;
            RebuildSteps();
        };
        OrganList.OnItemDeselected += _ =>
        {
            _selectedOrgan = null;
            RebuildSteps();
        };
    }

    public void UpdateState(OxydSurgeryState state)
    {
        _state = state;
        PatientLabel.Text = Loc.GetString("oxyd-surgery-patient", ("patient", state.PatientName));
        ToolLabel.Text = Loc.GetString("oxyd-surgery-held-tools",
            ("tool", string.IsNullOrEmpty(state.HeldItemName)
                ? Loc.GetString("oxyd-surgery-no-tool")
                : state.HeldItemName));

        OrganList.Clear();
        foreach (var organ in state.Organs)
        {
            var markers = new List<string>();
            if (organ.Incision != OxydIncisionStage.None)
                markers.Add(organ.Incision == OxydIncisionStage.Retracted ? "retracted" : "open");
            if (organ is { Incision: not OxydIncisionStage.None, Clamped: false })
                markers.Add("bleeding");
            // Eris hides wound details until the limb is diagnosed (scanner/probe).
            if (!organ.Diagnosed)
                markers.Add("undiagnosed");
            else
            {
                if (organ.Fractured)
                    markers.Add("fractured");
                if (organ.OrganDamage > 0)
                    markers.Add($"dmg {(int) organ.OrganDamage}");
                if (organ.EmbeddedCount > 0)
                    markers.Add($"embedded x{organ.EmbeddedCount}");
            }

            var suffix = markers.Count > 0 ? $" ({string.Join(", ", markers)})" : "";
            OrganList.AddItem($"{organ.Name}{suffix}", metadata: organ.Organ);
        }

        RebuildSteps();
    }

    private void RebuildSteps()
    {
        StepButtons.RemoveAllChildren();
        if (_state == null || _selectedOrgan is not { } sel)
        {
            OrganStatusLabel.Text = Loc.GetString("oxyd-surgery-select-organ");
            return;
        }

        var organ = _state.Organs.FirstOrDefault(o => o.Organ == sel);
        if (organ == null)
        {
            OrganStatusLabel.Text = Loc.GetString("oxyd-surgery-select-organ");
            return;
        }

        var flags = new List<string>
        {
            organ.External
                ? Loc.GetString("oxyd-surgery-flag-external")
                : Loc.GetString("oxyd-surgery-flag-internal"),
            organ.Robotic ? Loc.GetString("oxyd-surgery-flag-robotic") : "",
        };
        flags.RemoveAll(string.IsNullOrEmpty);
        OrganStatusLabel.Text = $"{organ.Name} — {string.Join(", ", flags)}";

        foreach (var step in organ.AvailableSteps)
        {
            var localStep = step;
            var button = new Button
            {
                Text = Loc.GetString($"oxyd-surgery-step-{step.ToString().ToLowerInvariant()}"),
            };
            button.OnPressed += _ => StepSelected?.Invoke(sel, localStep);
            StepButtons.AddChild(button);
        }
    }
}
