using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Faithful port of Eris's NanoUI surgery window (nano/templates/surgery_organ.tmpl +
/// surgery_internal.tmpl on the meat-mode skin): organ cards with the Mods/Wounds link on the
/// left, Diagnostics/Volume/Conditions cards on the right, and an internal view listing wound
/// cards, organ diagnostics and cavity modifications for the selected organ.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydSurgeryWindow : FancyWindow
{
    private const string MeatTexturePath = "/Textures/Oxyd/erisported/UI/uiBackground-Meat.png";

    private OxydSurgeryState? _state;
    private NetEntity? _selectedOrgan;
    /// <summary>Eris viewing_internal: true while the wound/mods view for _selectedOrgan is shown.</summary>
    private bool _viewInternal;

    public event Action<NetEntity, OxydSurgeryStep>? StepSelected;

    public OxydSurgeryWindow()
    {
        RobustXamlLoader.Load(this);

        MeatRoot.PanelOverride = new StyleBoxFlat(ErisSurgeryColors.MeatBg);
        var meat = IoCManager.Resolve<IResourceCache>().GetTexture(MeatTexturePath);
        var meatBox = new StyleBoxTexture
        {
            Texture = meat,
            Mode = StyleBoxTexture.StretchMode.Tile,
            TextureScale = Vector2.One * 0.5f,
        };
        meatBox.SetPatchMargin(StyleBox.Margin.All, 0);
        MeatTexture.PanelOverride = meatBox;
    }

    private void SelectStep(NetEntity organ, OxydSurgeryStep step) =>
        StepSelected?.Invoke(organ, step);

    private static string StepName(OxydSurgeryStep step) =>
        Loc.GetString($"oxyd-surgery-step-{step.ToString().ToLowerInvariant()}");

    public void UpdateState(OxydSurgeryState state)
    {
        _state = state;
        PatientLabel.Text = Loc.GetString("oxyd-surgery-patient",
            ("patient", state.PatientName));
        ToolLabel.Text = Loc.GetString("oxyd-surgery-held-tools",
            ("tool", string.IsNullOrEmpty(state.HeldItemName)
                ? Loc.GetString("oxyd-surgery-no-tool")
                : state.HeldItemName));
        PatientLabel.FontColorOverride = ErisSurgeryColors.Text;
        ToolLabel.FontColorOverride = ErisSurgeryColors.LabelText;

        // Keep the selection across state pushes; fall back to the first organ like Eris's view.
        var sel = _selectedOrgan;
        if (sel is not { } cur || state.Organs.All(o => o.Organ != cur))
        {
            sel = state.Organs.FirstOrDefault()?.Organ;
            _viewInternal = false;
        }
        _selectedOrgan = sel;

        Rebuild();
    }

    private void Rebuild()
    {
        ContentRoot.RemoveAllChildren();
        if (_state == null)
            return;

        if (_viewInternal && SelectedEntry() is { } organ)
            BuildInternalView(organ);
        else
            BuildExternalView();
    }

    private OxydSurgeryOrganEntry? SelectedEntry() =>
        _state?.Organs.FirstOrDefault(o => o.Organ == _selectedOrgan);

    // ------------------------------------------------------------------
    // External view (surgery_organ.tmpl else-branch)
    // ------------------------------------------------------------------

    private void BuildExternalView()
    {
        var state = _state!;

        var leftScroll = new ScrollContainer
        {
            SetWidth = 330,
            VerticalExpand = true,
            HScrollEnabled = false,
        };
        var cards = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 10, 0),
        };
        foreach (var organ in state.Organs)
            cards.AddChild(BuildOrganCard(organ));
        leftScroll.AddChild(cards);
        ContentRoot.AddChild(leftScroll);

        var right = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        right.AddChild(BuildDiagnosticsCard());
        right.AddChild(BuildVolumeCard());
        var condCard = BuildConditionsCard();
        condCard.VerticalExpand = true;
        right.AddChild(condCard);
        ContentRoot.AddChild(right);
    }

    /// <summary>Eris organ card: header (red underline when wounded/organic), 32px icon box,
    /// Mods/Wounds link, diagnosed bars, organ types, condition fixes, actions,
    /// then the amputate/insert footer on externals.</summary>
    private Control BuildOrganCard(OxydSurgeryOrganEntry organ)
    {
        var wounded = organ.Incision != OxydIncisionStage.None || organ.OrganDamage > 0 ||
                      organ.Fractured;
        var card = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
        };

        // <header><h3>name</h3></header> — red underline if organic + wounded.
        card.AddChild(MakeHeader(TitleCase(organ.Name),
            !organ.Robotic && wounded ? ErisSurgeryColors.WoundHeader : ErisSurgeryColors.CardBorder));

        // Icon box (.statusDisplayItem: black, #40628a border, 32x32) + Mods/Wounds link right.
        var headRow = new BoxContainer { SeparationOverride = 6, Margin = new Thickness(0, 4, 0, 4) };
        var iconBox = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat(Color.Black)
            {
                BorderColor = ErisSurgeryColors.CardBorder,
                BorderThickness = new Thickness(1),
            },
        };
        var sprite = new SpriteView { SetSize = new Vector2(32, 32), OverrideDirection = Direction.South };
        sprite.SetEntity(organ.Organ);
        iconBox.AddChild(sprite);
        headRow.AddChild(iconBox);

        var modsLink = new ErisLink(Loc.GetString("oxyd-surgery-mods-wounds"))
        {
            HorizontalAlignment = HAlignment.Right,
            HorizontalExpand = true,
        };
        var organNet = organ.Organ;
        modsLink.OnPressed += _ =>
        {
            _selectedOrgan = organNet;
            _viewInternal = true;
            Rebuild();
        };
        headRow.AddChild(modsLink);
        card.AddChild(headRow);

        if (organ.RunningStep is { } running)
            card.AddChild(MakeText(
                Loc.GetString("oxyd-surgery-running", ("step", StepName(running))),
                ErisSurgeryColors.WoundCountText));

        if (!organ.Diagnosed)
        {
            card.AddChild(MakeText(Loc.GetString("oxyd-surgery-undiagnosed"),
                ErisSurgeryColors.LabelText));
        }
        else
        {
            // Wounds count (orange).
            if (organ.WoundCount > 0)
            {
                var row = MakeSectionRow(Loc.GetString("oxyd-surgery-wounds-count"));
                row.AddChild(new Label { Text = organ.WoundCount.ToString(), FontColorOverride = ErisSurgeryColors.WoundCountText });
                card.AddChild(row);
            }

            // Oxygen bar (respiratory organs only).
            if (organ.ShowOxygen && _state != null)
            {
                var oxy = Math.Max(0f, _state.OwnerOxyMax - _state.OwnerOxyLoss);
                var row = MakeSectionRow(Loc.GetString("oxyd-surgery-oxygen"));
                row.AddChild(MakeBar(oxy / Math.Max(1f, _state.OwnerOxyMax),
                    ErisSurgeryColors.BarAverage,
                    $"{Math.Round(oxy, 1)} / {Math.Round(_state.OwnerOxyMax, 1)}"));
                card.AddChild(row);
            }

            // Health bar (good if undamaged else bad).
            if (organ.MaxDamage > 0)
            {
                var health = organ.MaxDamage - organ.OrganDamage;
                var row = MakeSectionRow(Loc.GetString("oxyd-surgery-health") + ":");
                row.AddChild(MakeBar(health / organ.MaxDamage,
                    organ.OrganDamage > 0 ? ErisSurgeryColors.BarBad : ErisSurgeryColors.BarGood,
                    $"{Math.Round(health, 1)} / {Math.Round(organ.MaxDamage, 1)}"));
                card.AddChild(row);
            }

            // Blood bar (red fill — 'bad' class in Eris).
            if (organ.MaxBlood > 0)
            {
                var row = MakeSectionRow(Loc.GetString("oxyd-surgery-blood"));
                row.AddChild(MakeBar(organ.StoredBlood / organ.MaxBlood,
                    ErisSurgeryColors.BarBad,
                    $"{Math.Round(organ.StoredBlood, 0)} / {Math.Round(organ.MaxBlood, 0)}"));
                card.AddChild(row);
            }

            // Organ types (efficiency): pink text inside a nested .display. Stacked + wrapped —
            // a side-by-side Label pair runs past the card edge instead of reflowing.
            if (organ.Processes.Count > 0)
            {
                var inner = new ErisPanel { Margin = new Thickness(0, 2, 0, 2) };
                var innerBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
                innerBox.AddChild(MakeText(Loc.GetString("oxyd-surgery-organ-types"),
                    ErisSurgeryColors.Text));
                innerBox.AddChild(MakeText(
                    string.Join(" ", organ.Processes.Select(p => $"{p} ({Math.Round(organ.Efficiency)}%)")),
                    ErisSurgeryColors.OrganTypeText));
                inner.AddChild(innerBox);
                card.AddChild(inner);
            }

            // Conditions + fix links (enabled when the session tool can run the fix).
            foreach (var (name, fix) in ConditionsFor(organ))
            {
                var row = MakeSectionRow($"{name}:");
                var fixLink = new ErisLink(StepName(fix)) { HorizontalExpand = true };
                if (organ.AvailableSteps.Contains(fix))
                {
                    var f = fix;
                    fixLink.OnPressed += _ => SelectStep(organNet, f);
                }
                else
                    fixLink.SetDisabledLook();
                row.AddChild(fixLink);
                card.AddChild(row);
            }
        }

        // Action links (Eris organ.actions). AvailableSteps is already stage- and
        // tool-filtered server-side, so every listed step is enabled here.
        foreach (var step in organ.AvailableSteps)
        {
            var row = new BoxContainer { Margin = new Thickness(0, 1, 0, 0) };
            var link = new ErisLink(StepName(step)) { HorizontalExpand = true };
            var s = step;
            link.OnPressed += _ => SelectStep(organNet, s);
            row.AddChild(link);
            card.AddChild(row);
        }

        // Eris footer links on the external organ card: Amputate/Disconnect (red) + Insert.
        if (organ.External)
        {
            var footer = new BoxContainer { SeparationOverride = 6, Margin = new Thickness(0, 4, 0, 0) };
            if (organ.AvailableSteps.Contains(OxydSurgeryStep.Amputate) ||
                organ.AvailableSteps.Contains(OxydSurgeryStep.DetachOrgan))
            {
                var amp = new ErisLink(
                    Loc.GetString(organ.Robotic ? "oxyd-surgery-disconnect" : "oxyd-surgery-amputate"),
                    red: true) { HorizontalExpand = true };
                amp.OnPressed += _ => SelectStep(organNet, OxydSurgeryStep.Amputate);
                footer.AddChild(amp);
            }
            if (organ.AvailableSteps.Contains(OxydSurgeryStep.InsertItem))
            {
                var ins = new ErisLink(Loc.GetString("oxyd-surgery-insert")) { HorizontalExpand = true };
                ins.OnPressed += _ => SelectStep(organNet, OxydSurgeryStep.InsertItem);
                footer.AddChild(ins);
            }
            if (footer.ChildCount > 0)
                card.AddChild(footer);
        }

        return new ErisPanel { Children = { card } };
    }



    /// <summary>Eris Diagnostics card for the selected organ: Health/Brute/Burn bars and
    /// green Efficiency; undiagnosed organs only offer the Diagnose link.</summary>
    private Control BuildDiagnosticsCard()
    {
        var organ = SelectedEntry();
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };
        box.AddChild(MakeHeader(Loc.GetString("oxyd-surgery-diagnostics")));

        if (organ == null)
        {
            box.AddChild(MakeText(Loc.GetString("oxyd-surgery-select-organ"),
                ErisSurgeryColors.LabelText));
        }
        else if (!organ.Diagnosed)
        {
            var diag = new ErisLink(Loc.GetString("oxyd-surgery-diagnose")) { HorizontalExpand = true };
            var net = organ.Organ;
            diag.OnPressed += _ => SelectStep(net, OxydSurgeryStep.DiagnoseWound);
            box.AddChild(diag);
        }
        else
        {
            var health = organ.MaxDamage - organ.OrganDamage;
            var row = MakeSectionRow(Loc.GetString("oxyd-surgery-health") + ":");
            row.AddChild(MakeBar(health / organ.MaxDamage,
                organ.OrganDamage > organ.MaxDamage / 2 ? ErisSurgeryColors.BarBad : ErisSurgeryColors.BarGood,
                $"{Math.Round(health, 1)} / {Math.Round(organ.MaxDamage, 1)}"));
            box.AddChild(row);

            var bruteRow = MakeSectionRow(Loc.GetString("oxyd-surgery-brute"));
            bruteRow.AddChild(MakeBar(organ.BruteDamage / organ.MaxDamage,
                ErisSurgeryColors.BarBad, $"{Math.Round(organ.BruteDamage, 1)}"));
            box.AddChild(bruteRow);

            var burnRow = MakeSectionRow(Loc.GetString("oxyd-surgery-burn"));
            burnRow.AddChild(MakeBar(organ.BurnDamage / organ.MaxDamage,
                ErisSurgeryColors.BarBad, $"{Math.Round(organ.BurnDamage, 1)}"));
            box.AddChild(burnRow);

            var effRow = MakeSectionRow(Loc.GetString("oxyd-surgery-efficiency-label"));
            effRow.AddChild(new Label
            {
                Text = Math.Round(organ.Efficiency).ToString(),
                FontColorOverride = ErisSurgeryColors.GoodText,
            });
            box.AddChild(effRow);
        }

        return new ErisPanel { Children = { box } };
    }

    /// <summary>Eris Volume card: occupied/max cavity (green/red) + Remove shrapnel link.</summary>
    private Control BuildVolumeCard()
    {
        var organ = SelectedEntry();
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };
        box.AddChild(MakeHeader(Loc.GetString("oxyd-surgery-volume")));

        if (organ != null)
        {
            var row = MakeSectionRow(Loc.GetString("oxyd-surgery-occupied-label"));
            // Occupied space: green when within capacity, red when over.
            var over = organ.EmbeddedCount > organ.CavityMax;
            row.AddChild(new Label
            {
                Text = $"{organ.EmbeddedCount} / {organ.CavityMax}",
                FontColorOverride = over ? ErisSurgeryColors.BadText : ErisSurgeryColors.GoodText,
            });
            box.AddChild(row);

            if (organ.EmbeddedCount > 0)
            {
                var link = new ErisLink(Loc.GetString("oxyd-surgery-remove-shrapnel")) { HorizontalExpand = true };
                var net = organ.Organ;
                if (organ.AvailableSteps.Contains(OxydSurgeryStep.RemoveEmbedded) ||
                    organ.AvailableSteps.Contains(OxydSurgeryStep.ExtractShrapnel))
                {
                    var step = organ.AvailableSteps.Contains(OxydSurgeryStep.RemoveEmbedded)
                        ? OxydSurgeryStep.RemoveEmbedded
                        : OxydSurgeryStep.ExtractShrapnel;
                    link.OnPressed += _ => SelectStep(net, step);
                }
                else
                    link.SetDisabledLook();
                box.AddChild(link);
            }
        }

        return new ErisPanel { Children = { box } };
    }

    /// <summary>Eris Conditions card: every diagnosed organ's fixable conditions across the body.</summary>
    private Control BuildConditionsCard()
    {
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };
        box.AddChild(MakeHeader(Loc.GetString("oxyd-surgery-conditions")));

        var scroll = new ScrollContainer { VerticalExpand = true, HScrollEnabled = false };
        var rows = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 10, 0),
        };

        var any = false;
        if (_state != null)
        {
            foreach (var organ in _state.Organs)
            {
                if (!organ.Diagnosed)
                    continue;
                foreach (var (name, fix) in ConditionsFor(organ))
                {
                    any = true;
                    var row = MakeSectionRow($"{TitleCase(organ.Name)} — {name}:", width: 0);
                    var link = new ErisLink(StepName(fix)) { HorizontalExpand = true };
                    if (organ.AvailableSteps.Contains(fix))
                    {
                        var net = organ.Organ;
                        var f = fix;
                        link.OnPressed += _ => SelectStep(net, f);
                    }
                    else
                        link.SetDisabledLook();
                    row.AddChild(link);
                    rows.AddChild(row);
                }
            }
        }
        if (!any)
            rows.AddChild(MakeText("—", ErisSurgeryColors.LabelText));

        scroll.AddChild(rows);
        box.AddChild(scroll);
        return new ErisPanel { Children = { box } };
    }

    // ------------------------------------------------------------------
    // Internal view (surgery_internal.tmpl): wounds, diagnostics, modifications
    // ------------------------------------------------------------------

    private void BuildInternalView(OxydSurgeryOrganEntry organ)
    {
        // Left: Wounds panel with one nanoMap card per wound.
        var left = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            SetWidth = 330,
            VerticalExpand = true,
        };
        var woundsBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };
        woundsBox.AddChild(MakeHeader(Loc.GetString("oxyd-surgery-wounds")));
        var wscroll = new ScrollContainer { VerticalExpand = true, HScrollEnabled = false };
        var wrows = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 10, 0),
        };
        if (organ.Wounds.Count == 0)
        {
            wrows.AddChild(MakeText(
                Loc.GetString(organ.Diagnosed ? "oxyd-surgery-no-wounds" : "oxyd-surgery-undiagnosed"),
                ErisSurgeryColors.LabelText));
        }
        foreach (var wound in organ.Wounds)
            wrows.AddChild(BuildWoundCard(organ, wound));
        wscroll.AddChild(wrows);
        woundsBox.AddChild(wscroll);
        left.AddChild(new ErisPanel { Children = { woundsBox }, VerticalExpand = true });
        ContentRoot.AddChild(left);

        // Right: return link, Diagnostics - organ, Modifications.
        var right = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };

        var retBox = new BoxContainer();
        var ret = new ErisLink(Loc.GetString("oxyd-surgery-internal-return")) { HorizontalExpand = true };
        ret.OnPressed += _ =>
        {
            _viewInternal = false;
            Rebuild();
        };
        retBox.AddChild(ret);
        right.AddChild(new ErisPanel { Children = { retBox } });

        var diagBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };
        diagBox.AddChild(MakeHeader(Loc.GetString("oxyd-surgery-internal-diagnostics",
            ("organ", TitleCase(organ.Name)))));
        if (organ.Diagnosed)
        {
            var health = organ.MaxDamage - organ.OrganDamage;
            var row = MakeSectionRow(Loc.GetString("oxyd-surgery-health") + ":");
            row.AddChild(MakeBar(health / organ.MaxDamage,
                organ.OrganDamage > organ.MaxDamage / 2 ? ErisSurgeryColors.BarBad : ErisSurgeryColors.BarGood,
                $"{Math.Round(health, 1)} / {Math.Round(organ.MaxDamage, 1)}"));
            diagBox.AddChild(row);

            if (organ.MaxBlood > 0)
            {
                var brow = MakeSectionRow(Loc.GetString("oxyd-surgery-blood"));
                brow.AddChild(MakeBar(organ.StoredBlood / organ.MaxBlood,
                    ErisSurgeryColors.BarBad,
                    $"{Math.Round(organ.StoredBlood, 0)} / {Math.Round(organ.MaxBlood, 0)}"));
                diagBox.AddChild(brow);
            }
        }
        var examine = new ErisLink(Loc.GetString("oxyd-surgery-examine")) { HorizontalExpand = true };
        if (!organ.Diagnosed || organ.AvailableSteps.Contains(OxydSurgeryStep.DiagnoseWound))
        {
            var net = organ.Organ;
            examine.OnPressed += _ => SelectStep(net, OxydSurgeryStep.DiagnoseWound);
        }
        else
            examine.SetDisabledLook();
        diagBox.AddChild(examine);
        right.AddChild(new ErisPanel { Children = { diagBox } });

        var modsBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };
        modsBox.AddChild(MakeHeader(Loc.GetString("oxyd-surgery-modifications")));
        var modCard = new ErisNanoMapPanel();
        var modList = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 2 };
        if (organ.ModNames.Count == 0)
        {
            modList.AddChild(new Label
            {
                Text = Loc.GetString("oxyd-surgery-no-mods"),
                FontColorOverride = ErisSurgeryColors.LabelText,
            });
        }
        foreach (var mod in organ.ModNames)
            modList.AddChild(new Label { Text = mod, FontColorOverride = ErisSurgeryColors.Text });
        modCard.AddChild(modList);
        modsBox.AddChild(modCard);

        var attach = new ErisLink(Loc.GetString("oxyd-surgery-attach")) { HorizontalExpand = true };
        var remove = new ErisLink(Loc.GetString("oxyd-surgery-remove")) { HorizontalExpand = true };
        var organNet = organ.Organ;
        if (organ.AvailableSteps.Contains(OxydSurgeryStep.InsertItem))
            attach.OnPressed += _ => SelectStep(organNet, OxydSurgeryStep.InsertItem);
        else
            attach.SetDisabledLook();
        if (organ.AvailableSteps.Contains(OxydSurgeryStep.RemoveItem) ||
            organ.AvailableSteps.Contains(OxydSurgeryStep.RemoveEmbedded))
        {
            var step = organ.AvailableSteps.Contains(OxydSurgeryStep.RemoveItem)
                ? OxydSurgeryStep.RemoveItem
                : OxydSurgeryStep.RemoveEmbedded;
            remove.OnPressed += _ => SelectStep(organNet, step);
        }
        else
            remove.SetDisabledLook();
        modsBox.AddChild(attach);
        modsBox.AddChild(remove);
        right.AddChild(new ErisPanel { Children = { modsBox } });

        // Scroll the stacked panels so a long mods/wounds list can't run past the window bottom.
        var rightScroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            HScrollEnabled = false,
        };
        rightScroll.AddChild(right);
        ContentRoot.AddChild(rightScroll);
    }

    /// <summary>Eris wound card (.nanoMap): Type / Severity x/max / Treatments / Treat link.</summary>
    private Control BuildWoundCard(OxydSurgeryOrganEntry organ, OxydSurgeryWoundEntry wound)
    {
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 2 };

        var typeRow = new BoxContainer { SeparationOverride = 6 };
        typeRow.AddChild(new Label { Text = Loc.GetString("oxyd-surgery-type"), FontColorOverride = ErisSurgeryColors.ItemLabelText, SetWidth = 80, ClipText = true });
        typeRow.AddChild(MakeText(wound.Name, ErisSurgeryColors.Text));
        box.AddChild(typeRow);

        var sevRow = new BoxContainer { SeparationOverride = 6 };
        sevRow.AddChild(new Label { Text = Loc.GetString("oxyd-surgery-severity"), FontColorOverride = ErisSurgeryColors.ItemLabelText, SetWidth = 80, ClipText = true });
        sevRow.AddChild(MakeText($"{wound.Severity} / {wound.SeverityMax}", ErisSurgeryColors.Text));
        box.AddChild(sevRow);

        var treatRow = new BoxContainer { SeparationOverride = 6 };
        treatRow.AddChild(new Label { Text = Loc.GetString("oxyd-surgery-treatments"), FontColorOverride = ErisSurgeryColors.ItemLabelText, SetWidth = 80, ClipText = true });
        treatRow.AddChild(MakeText(wound.Treatments, ErisSurgeryColors.Text));
        box.AddChild(treatRow);

        if (wound.FixStep is { } fix)
        {
            var link = new ErisLink(Loc.GetString("oxyd-surgery-treat")) { HorizontalExpand = true };
            if (organ.AvailableSteps.Contains(fix))
                link.OnPressed += _ => SelectStep(organ.Organ, fix);
            else
                link.SetDisabledLook();
            box.AddChild(link);
        }

        return new ErisNanoMapPanel { Children = { box } };
    }

    // ------------------------------------------------------------------
    // Shared builders
    // ------------------------------------------------------------------

    /// <summary>Eris condition list: (label, fixing step) — matches the server's BuildWounds set.</summary>
    private static List<(string Name, OxydSurgeryStep Fix)> ConditionsFor(OxydSurgeryOrganEntry organ)
    {
        var list = new List<(string, OxydSurgeryStep)>();
        if (organ is { Incision: not OxydIncisionStage.None, Clamped: false })
            list.Add((Loc.GetString("oxyd-surgery-cond-bleeding"), OxydSurgeryStep.FixBleeding));
        if (organ.Fractured)
            list.Add((Loc.GetString("oxyd-surgery-cond-fracture"), OxydSurgeryStep.MendBone));
        if (organ.EmbeddedCount > 0)
            list.Add((Loc.GetString("oxyd-surgery-cond-embedded"), OxydSurgeryStep.RemoveEmbedded));
        if (organ is { OrganDamage: > 0, Robotic: false })
            list.Add((Loc.GetString("oxyd-surgery-cond-damage"), OxydSurgeryStep.FixOrgan));
        if (organ is { OrganDamage: > 0, Robotic: true })
            list.Add((Loc.GetString("oxyd-surgery-cond-robo"), OxydSurgeryStep.RoboFixBrute));
        return list;
    }

    /// <summary>Eris &lt;header&gt;&lt;h3&gt;: white heading over a 2px accent underline.</summary>
    private static Control MakeHeader(string text, Color? underline = null)
    {
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 2 };
        box.AddChild(new Label
        {
            Text = text,
            StyleClasses = { StyleClass.LabelSubHeading },
            FontColorOverride = Color.White,
        });
        box.AddChild(new PanelContainer
        {
            MinHeight = 2,
            PanelOverride = new StyleBoxFlat(underline ?? ErisSurgeryColors.CardBorder),
        });
        return box;
    }

    /// <summary>Eris &lt;section&gt;: a .label cell then a .content cell. The label cell is a
    /// fixed-width column (default 130px, fits "Occupied space:" etc.) with ClipText so
    /// overlong labels truncate instead of drawing over the value — ClipText without an
    /// explicit width collapses the label's measure to zero, so the width must stay.
    /// Pass width 0 for a natural-width label in a roomy row (e.g. the Conditions card).</summary>
    private static BoxContainer MakeSectionRow(string label, float width = 130)
    {
        var cell = new Label
        {
            Text = label,
            FontColorOverride = ErisSurgeryColors.LabelText,
            HorizontalExpand = false,
        };
        if (width > 0)
        {
            cell.SetWidth = width;
            cell.ClipText = true;
        }
        var row = new BoxContainer { SeparationOverride = 6 };
        row.AddChild(cell);
        return row;
    }

    /// <summary>Wrapping body text — nanoUI reflows long lines inside the card; a plain
    /// Label just draws past the card bounds. RichTextLabel wraps at its own width.</summary>
    private static RichTextLabel MakeText(string text, Color color)
    {
        var label = new RichTextLabel { HorizontalExpand = true };
        label.SetMessage(text, color);
        return label;
    }

    private static ErisBar MakeBar(float fraction, Color fill, string text)
    {
        var bar = new ErisBar { HorizontalExpand = true };
        bar.SetValue(fraction, fill, text);
        return bar;
    }

    private static string TitleCase(string name) =>
        string.IsNullOrEmpty(name) ? name : string.Concat(name[..1].ToUpperInvariant(), name[1..]);
}
