using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class OxydMircUiFragment : BoxContainer
{
    public OxydMircUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(List<OxydMircEntry> entries)
    {
        EntryContainer.RemoveAllChildren();
        foreach (var entry in entries)
            EntryContainer.AddChild(BuildEntry(entry));
    }

    private static Control BuildEntry(OxydMircEntry entry)
    {
        var card = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 2,
            Margin = new Thickness(6, 4),
        };
        card.AddChild(new Label { Text = entry.Name, StyleClasses = { "LabelHeading" } });
        card.AddChild(Wrapped(entry.Description));
        foreach (var recipe in entry.Recipes)
        {
            card.AddChild(Wrapped(recipe));
        }
        if (entry.Recipes.Count == 0)
            card.AddChild(new Label { Text = Loc.GetString("oxyd-mirc-no-recipe") });
        return card;
    }

    private static RichTextLabel Wrapped(string text)
    {
        var label = new RichTextLabel { HorizontalExpand = true };
        label.SetMessage(text);
        return label;
    }
}
