using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class OxydScannerWindow : FancyWindow
{
    public OxydScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(OxydScannerState state)
    {
        PatientLabel.Text = state.HasScan
            ? Loc.GetString("oxyd-scanner-patient", ("name", state.PatientName))
            : Loc.GetString("oxyd-scanner-none");

        if (!state.HasScan)
        {
            VitalsLabel.Text = "";
            ExtrasLabel.Text = "";
            OrganList.Clear();
            return;
        }

        VitalsLabel.Text = Loc.GetString("oxyd-scanner-vitals",
            ("health", (int) state.Health),
            ("brute", (int) state.BruteLoss),
            ("burn", (int) state.BurnLoss),
            ("toxin", (int) state.ToxinLoss),
            ("oxy", (int) state.OxyLoss));
        ExtrasLabel.Text = Loc.GetString("oxyd-scanner-extras",
            ("pain", (int) state.Pain),
            ("nsa", (int) state.Nsa),
            ("blood", (int) state.BloodLevel),
            ("bloodmax", (int) state.BloodMax));

        OrganList.Clear();
        foreach (var organ in state.Organs)
            OrganList.AddItem($"{organ.Name}: {organ.Status} ({(int) organ.Damage})");
    }
}
