using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris bioprinter window: biomass displayBar, blood-sample status line, then a
/// card per printable organ with its cost and a Print pill (Eris products table
/// rendered in the shared NanoUI style).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydBioprinterWindow : FancyWindow
{
    public event Action<string>? PrintRequested;

    private readonly ErisBar _matterBar = new();
    private readonly Label _matterLabel = new();
    private readonly Label _sampleLabel = new();
    private readonly Label _workingLabel = new();
    private readonly BoxContainer _products = new();

    public OxydBioprinterWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));

        var head = new ErisItemLabel(Loc.GetString("oxyd-bioprinter-matter"));
        head.Margin = new Thickness(0, 0, 0, 2);
        Content.AddChild(head);
        Content.AddChild(_matterBar);
        _matterLabel.FontColorOverride = ErisSurgeryColors.LabelText;
        Content.AddChild(_matterLabel);
        _sampleLabel.FontColorOverride = ErisSurgeryColors.ItemLabelText;
        Content.AddChild(_sampleLabel);
        _workingLabel.FontColorOverride = ErisSurgeryColors.WoundCountText;
        Content.AddChild(_workingLabel);
        Content.AddChild(_products);
    }

    public void UpdateState(OxydBioprinterState state)
    {
        var frac = state.MaxMatter > 0 ? (float) state.StoredMatter / state.MaxMatter : 0f;
        _matterBar.SetValue(frac, ErisSurgeryColors.BarDefault, $"{state.StoredMatter} / {state.MaxMatter}");
        _sampleLabel.Text = state.HasBloodSample
            ? Loc.GetString("oxyd-bioprinter-sample-yes")
            : Loc.GetString("oxyd-bioprinter-sample-no");
        _workingLabel.Text = state.Working ? Loc.GetString("oxyd-bioprinter-working") : string.Empty;

        _products.RemoveAllChildren();
        var i = 0;
        foreach (var p in state.Products)
        {
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
            var name = new Label
            {
                Text = $"{p.Name} — {p.Cost}",
                FontColorOverride = ErisSurgeryColors.Text,
                HorizontalExpand = true,
            };
            var btn = new ErisLink(Loc.GetString("oxyd-bioprinter-print"));
            if (p.Affordable)
            {
                var id = p.Id;
                btn.OnPressed += _ => PrintRequested?.Invoke(id);
            }
            else
            {
                btn.SetDisabledLook();
            }
            row.AddChild(name);
            row.AddChild(btn);
            _products.AddChild(ErisCandystripe.Wrap(row, i++));
        }
    }
}
