using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris handheld health-scanner readout (adv_med_scanner.dm output): "Analyzing
/// Results for X", a colored Overall Status, the colored Key legend
/// (Suffocation OX / Toxin TX / Brute BR / Burns BU), the colored
/// "Damage Specifics" quartet, body temperature in °C (°F), then a colored
/// localized-damage list per limb and the blood-level line.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydScannerWindow : FancyWindow
{
    private static readonly Color SuffBlue = Color.FromHex("#0080ff");
    private static readonly Color ToxGreen = Color.FromHex("#008000");
    private static readonly Color BruteRed = Color.FromHex("#ff0000");
    private static readonly Color BurnOrange = Color.FromHex("#FFA500");

    public OxydScannerWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));
    }

    public void UpdateState(OxydScannerState state)
    {
        Content.RemoveAllChildren();

        if (!state.HasScan)
        {
            Content.AddChild(new ErisItemLabel(Loc.GetString("oxyd-scanner-none")));
            return;
        }

        Content.AddChild(new ErisItemLabel(Loc.GetString("oxyd-scanner-analyzing",
            ("name", state.PatientName))));

        // Overall Status, colored by living state.
        var (statusText, statusColor) = !state.Alive
            ? (Loc.GetString("oxyd-scanner-status-dead"), ErisSurgeryColors.BadText)
            : state.Critical
                ? (Loc.GetString("oxyd-scanner-status-crit"), BurnOrange)
                : (Loc.GetString("oxyd-scanner-status-alive"), ToxGreen);
        var statusRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };
        statusRow.AddChild(new Label
        {
            Text = Loc.GetString("oxyd-scanner-overall", ("status", "")),
            FontColorOverride = ErisSurgeryColors.Text,
        });
        statusRow.AddChild(new Label { Text = statusText, FontColorOverride = statusColor });
        Content.AddChild(statusRow);

        // Key legend (Eris colored two-letter codes).
        var keyRow = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 8 };
        keyRow.AddChild(new ErisItemLabel(Loc.GetString("oxyd-scanner-key")));
        keyRow.AddChild(Colored("Suffocation", SuffBlue));
        keyRow.AddChild(Colored("Toxin", ToxGreen));
        keyRow.AddChild(Colored("Brute", BruteRed));
        keyRow.AddChild(Colored("Burns", BurnOrange));
        Content.AddChild(keyRow);

        // Damage Specifics: colored OX-TX-BR-BU values.
        var spec = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
        spec.AddChild(new ErisItemLabel(Loc.GetString("oxyd-scanner-damage-specifics")));
        spec.AddChild(Colored($"{(int) state.OxyLoss}", SuffBlue));
        spec.AddChild(Colored("-", ErisSurgeryColors.LabelText));
        spec.AddChild(Colored($"{(int) state.ToxinLoss}", ToxGreen));
        spec.AddChild(Colored("-", ErisSurgeryColors.LabelText));
        spec.AddChild(Colored($"{(int) state.BruteLoss}", BruteRed));
        spec.AddChild(Colored("-", ErisSurgeryColors.LabelText));
        spec.AddChild(Colored($"{(int) state.BurnLoss}", BurnOrange));
        Content.AddChild(spec);

        // Body temperature °C (°F).
        var celsius = state.Temperature - 273.15f;
        var fahrenheit = celsius * 9f / 5f + 32f;
        Content.AddChild(new Label
        {
            Text = Loc.GetString("oxyd-scanner-body-temp",
                ("celsius", $"{celsius:0.0}"), ("fahrenheit", $"{fahrenheit:0.0}")),
            FontColorOverride = ErisSurgeryColors.Text,
        });

        // Localized damage: colored severity per limb, "Limbs are OK." when clean.
        Content.AddChild(new ErisItemLabel(Loc.GetString("oxyd-scanner-loc-damage")));
        var anyDamage = false;
        foreach (var organ in state.Organs)
        {
            if (organ.Damage <= 0 && !organ.Fractured && !organ.Bleeding)
                continue;
            anyDamage = true;
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
            row.AddChild(new Label
            {
                Text = organ.Name,
                FontColorOverride = ErisSurgeryColors.Text,
            });
            row.AddChild(new Label
            {
                Text = $"{organ.Status} ({(int) organ.Damage})",
                FontColorOverride = SeverityColor(organ.Damage),
            });
            Content.AddChild(row);
        }
        if (!anyDamage)
            Content.AddChild(new Label
            {
                Text = Loc.GetString("oxyd-scanner-limbs-ok"),
                FontColorOverride = ToxGreen,
            });

        // Blood level line, colored by severity like Eris.
        var bloodPct = state.BloodMax > 0 ? state.BloodLevel / state.BloodMax * 100f : 0f;
        var (bloodKey, bloodColor) = bloodPct switch
        {
            < 60f => ("oxyd-scanner-blood-crit", BruteRed),
            < 90f => ("oxyd-scanner-blood-low", BurnOrange),
            _ => ("oxyd-scanner-blood-normal", ToxGreen),
        };
        Content.AddChild(new Label
        {
            Text = Loc.GetString("oxyd-scanner-blood-level",
                ("status", Loc.GetString(bloodKey)),
                ("pct", (int) bloodPct), ("volume", (int) state.BloodLevel)),
            FontColorOverride = bloodColor,
        });

        // Eris "Pulse : ..." line, colored by classification.
        var (pulseKey, pulseColor) = state.Pulse switch
        {
            OxydPulse.None => ("oxyd-pulse-none", BruteRed),
            OxydPulse.Thready => ("oxyd-pulse-thready", BurnOrange),
            OxydPulse.Irregular => ("oxyd-pulse-irregular", BurnOrange),
            _ => ("oxyd-pulse-norm", ToxGreen),
        };
        Content.AddChild(new Label
        {
            Text = Loc.GetString("oxyd-scanner-pulse-line",
                ("pulse", Loc.GetString(pulseKey))),
            FontColorOverride = pulseColor,
        });

        // Port extras (no Eris equivalent but the data is real): pain + NSA load.
        if (state.Pain > 0)
        {
            Content.AddChild(new Label
            {
                Text = $"Pain: {(int) state.Pain}",
                FontColorOverride = ErisSurgeryColors.LabelText,
            });
        }
        if (state.Nsa > 0)
        {
            Content.AddChild(new Label
            {
                Text = $"NSA: {(int) state.Nsa}",
                FontColorOverride = ErisSurgeryColors.LabelText,
            });
        }
    }

    private static Color SeverityColor(float damage) => damage switch
    {
        > 40f => BruteRed,
        > 20f => BurnOrange,
        > 0f => ErisSurgeryColors.BarAverage,
        _ => ToxGreen,
    };

    private static Label Colored(string text, Color color) => new()
    {
        Text = text,
        FontColorOverride = color,
    };
}
