using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris MIRC cartridge (chemistry_catalog.tmpl): three-stage flow —
/// splash (Moebius logo + title + Browse link), reagent list (search field +
/// Name/Phase/Type candystripe table of linked names), then the entry page
/// (PRINT/BACK row, description, the Type/Phase/Color/Metabolism/NSA spec rows,
/// taste, "Takes part in reactions" and synthesis-recipe link boxes).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydMircUiFragment : BoxContainer
{
    private const string LogoTexturePath = "/Textures/Oxyd/erisported/UI/moebus_logo.png";

    private enum Stage { Splash, List, Entry }

    private List<OxydMircEntry> _entries = new();
    private Stage _stage = Stage.Splash;
    private OxydMircEntry? _current;
    private string _filter = string.Empty;
    private LineEdit? _searchBox;

    public OxydMircUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));
    }

    public void UpdateState(List<OxydMircEntry> entries)
    {
        _entries = entries;
        // Re-resolve the open entry against fresh data; stay on the same stage.
        if (_current is { } cur)
            _current = _entries.FirstOrDefault(e => e.Id == cur.Id);
        Rebuild();
    }

    private void Rebuild()
    {
        EntryContainer.RemoveAllChildren();
        switch (_stage)
        {
            case Stage.Splash:
                BuildSplash();
                break;
            case Stage.List:
                BuildList();
                break;
            case Stage.Entry:
                if (_current is { } entry)
                    BuildEntryPage(entry);
                else
                    BuildList();
                break;
        }
    }

    // ---------------- Splash (chemistry_catalog.tmpl) ----------------

    private void BuildSplash()
    {
        var logo = new TextureRect
        {
            Texture = IoCManager.Resolve<IResourceCache>().GetTexture(LogoTexturePath),
            HorizontalAlignment = HAlignment.Center,
            MinSize = new Vector2(200, 96),
            Margin = new Thickness(0, 8),
        };
        EntryContainer.AddChild(logo);

        var title = new Label
        {
            Text = Loc.GetString("oxyd-mirc-splash-title"),
            FontColorOverride = ErisSurgeryColors.ItemLabelText,
            HorizontalAlignment = HAlignment.Center,
        };
        EntryContainer.AddChild(title);

        var welcome = new Label
        {
            Text = Loc.GetString("oxyd-mirc-splash-welcome"),
            FontColorOverride = ErisSurgeryColors.Text,
            HorizontalAlignment = HAlignment.Center,
        };
        EntryContainer.AddChild(welcome);

        var browse = new ErisLink(Loc.GetString("oxyd-mirc-splash-browse"));
        browse.HorizontalAlignment = HAlignment.Center;
        browse.Margin = new Thickness(0, 8, 0, 0);
        browse.OnPressed += _ =>
        {
            _stage = Stage.List;
            Rebuild();
        };
        EntryContainer.AddChild(browse);
    }

    // ---------------- Reagent list (catalog_list_reagents.tmpl) ----------------

    private void BuildList()
    {
        var searchRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            Margin = new Thickness(0, 0, 0, 6),
        };
        searchRow.AddChild(new ErisItemLabel(Loc.GetString("oxyd-mirc-search")));
        _searchBox = new LineEdit
        {
            Text = _filter,
            HorizontalExpand = true,
            PlaceHolder = "...",
        };
        _searchBox.OnTextChanged += args =>
        {
            _filter = args.Text;
            BuildList();
        };
        searchRow.AddChild(_searchBox);
        EntryContainer.AddChild(searchRow);

        // Table header: Name | Phase | Type
        var header = new GridContainer
        {
            Columns = 3,
            HorizontalExpand = true,
        };
        header.AddChild(new ErisItemLabel(Loc.GetString("oxyd-mirc-col-name")));
        header.AddChild(new ErisItemLabel(Loc.GetString("oxyd-mirc-col-phase")));
        header.AddChild(new ErisItemLabel(Loc.GetString("oxyd-mirc-col-type")));
        EntryContainer.AddChild(header);

        var index = 0;
        foreach (var entry in _entries)
        {
            if (!string.IsNullOrEmpty(_filter) &&
                !entry.Name.Contains(_filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var row = new GridContainer
            {
                Columns = 3,
                HorizontalExpand = true,
            };
            var local = entry;
            var link = new ErisLink(entry.Name) { HorizontalExpand = true };
            link.OnPressed += _ =>
            {
                _current = local;
                _stage = Stage.Entry;
                Rebuild();
            };
            row.AddChild(link);
            row.AddChild(new ErisSubLabel(entry.Phase));
            row.AddChild(new ErisSubLabel(entry.Type));
            EntryContainer.AddChild(ErisCandystripe.Wrap(row, index++));
        }
    }

    // ---------------- Entry page (catalog_entry_reagent.tmpl) ----------------

    private void BuildEntryPage(OxydMircEntry entry)
    {
        // PRINT + BACK on the right (PRINT is decorative — a report printer feature
        // doesn't exist; keep the Eris button disabled rather than fake it).
        var topRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        topRow.AddChild(new Control { HorizontalExpand = true });
        var print = new ErisLink(Loc.GetString("oxyd-mirc-print"));
        print.SetDisabledLook();
        print.ToolTip = Loc.GetString("oxyd-mirc-no-recipe");
        topRow.AddChild(print);
        var back = new ErisLink(Loc.GetString("oxyd-mirc-back"));
        back.OnPressed += _ =>
        {
            _stage = Stage.List;
            Rebuild();
        };
        topRow.AddChild(back);
        EntryContainer.AddChild(topRow);

        var title = new Label
        {
            Text = entry.Name,
            FontColorOverride = ErisSurgeryColors.ItemLabelText,
            StyleClasses = { "LabelHeading" },
        };
        EntryContainer.AddChild(title);
        EntryContainer.AddChild(Wrapped(entry.Description, ErisSurgeryColors.Text));

        // Specifications: itemLabel rows.
        var specs = new ErisStatusBox { HorizontalExpand = true, Margin = new Thickness(0, 6) };
        var specCol = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 3,
        };
        specs.AddChild(specCol);
        specCol.AddChild(Spec(Loc.GetString("oxyd-mirc-entry-type"), entry.Type));
        specCol.AddChild(Spec(Loc.GetString("oxyd-mirc-entry-phase"), entry.Phase));

        var colorRow = new ErisSpecRow(Loc.GetString("oxyd-mirc-entry-color"));
        colorRow.AddValue(new PanelContainer
        {
            MinSize = new Vector2(16, 12),
            PanelOverride = new StyleBoxFlat(Color.FromHex(entry.ColorHex, Color.White)),
        });
        colorRow.AddValue(new ErisSubLabel(entry.ColorHex));
        specCol.AddChild(colorRow);

        specCol.AddChild(Spec(Loc.GetString("oxyd-mirc-entry-metabolism"),
            $"{entry.Metabolism:0.###} u/s in blood"));
        if (entry.Nsa >= 0f)
            specCol.AddChild(Spec(Loc.GetString("oxyd-mirc-entry-nsa"), $"{entry.Nsa:0.##} units"));
        if (entry.AddictionThreshold >= 0f)
        {
            specCol.AddChild(Spec(Loc.GetString("oxyd-mirc-entry-addiction"),
                $"{entry.AddictionThreshold:0.#} units, {entry.AddictionChance:0.##}%"));
        }
        if (!string.IsNullOrEmpty(entry.Taste))
            specCol.AddChild(Spec(Loc.GetString("oxyd-mirc-entry-taste"), entry.Taste));
        EntryContainer.AddChild(specs);

        // "Takes part in reactions" — catalogEntryLink pills.
        if (entry.UsedIn.Count > 0)
        {
            var usedBox = new ErisStatusBox { HorizontalExpand = true, Margin = new Thickness(0, 6) };
            var usedCol = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 3,
            };
            usedBox.AddChild(usedCol);
            usedCol.AddChild(new ErisItemLabel(Loc.GetString("oxyd-mirc-entry-used-in")));
            var linkRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };
            foreach (var used in entry.UsedIn.DistinctBy(l => l.Label))
            {
                var local = used;
                if (local.EntryId == null)
                {
                    linkRow.AddChild(new ErisSubLabel(local.Label));
                    continue;
                }
                var link = new ErisLink(local.Label);
                link.OnPressed += _ =>
                {
                    _current = _entries.FirstOrDefault(e => e.Id == local.EntryId) ?? _current;
                    Rebuild();
                };
                linkRow.AddChild(link);
            }
            usedCol.AddChild(linkRow);
            EntryContainer.AddChild(usedBox);
        }

        // Synthesis recipes.
        if (entry.Recipes.Count > 0)
        {
            var recipeBox = new ErisStatusBox { HorizontalExpand = true, Margin = new Thickness(0, 6) };
            var recipeCol = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 3,
            };
            recipeBox.AddChild(recipeCol);
            recipeCol.AddChild(new ErisItemLabel(Loc.GetString("oxyd-mirc-entry-recipes")));
            foreach (var recipe in entry.Recipes)
                recipeCol.AddChild(Wrapped(recipe, ErisSurgeryColors.Text));
            EntryContainer.AddChild(recipeBox);
        }
    }

    private static ErisSpecRow Spec(string label, string value)
    {
        var row = new ErisSpecRow(label, 110f);
        row.AddValue(new Label { Text = value, FontColorOverride = ErisSurgeryColors.Text });
        return row;
    }

    private static RichTextLabel Wrapped(string text, Color color)
    {
        var label = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        label.SetMessage($"[color={color.ToHex()}]{text}[/color]");
        return label;
    }
}
