using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class OxydSleeperWindow : FancyWindow
{
    public event Action<string>? InjectRequested;
    public event Action? EjectRequested;
    public event Action? EjectBeakerRequested;

    public OxydSleeperWindow()
    {
        RobustXamlLoader.Load(this);

        EjectButton.OnPressed += _ => EjectRequested?.Invoke();
        EjectBeakerButton.OnPressed += _ => EjectBeakerRequested?.Invoke();
    }

    public void UpdateState(OxydSleeperState state)
    {
        OccupantLabel.Text = state.HasOccupant
            ? Loc.GetString("oxyd-sleeper-occupant", ("name", state.OccupantName))
            : Loc.GetString("oxyd-sleeper-empty");
        HealthLabel.Text = state.HasOccupant
            ? Loc.GetString("oxyd-sleeper-health", ("health", (int) state.OccupantHealth))
            : "";

        ChemButtons.RemoveAllChildren();
        if (state.HasOccupant)
        {
            foreach (var chem in state.Chems)
            {
                var local = chem.Reagent;
                var button = new Button
                {
                    Text = Loc.GetString("oxyd-sleeper-inject-chem",
                        ("name", chem.Name), ("dose", chem.DoseSize), ("current", (int) chem.InPatient)),
                    Disabled = !chem.Enabled,
                };
                if (chem.DisabledReason != null)
                    button.ToolTip = chem.DisabledReason;
                button.OnPressed += _ => InjectRequested?.Invoke(local);
                ChemButtons.AddChild(button);
            }
        }

        BeakerLabel.Text = state.HasBeaker
            ? Loc.GetString("oxyd-sleeper-beaker", ("vol", (int) state.BeakerVolume), ("max", (int) state.BeakerMaxVolume))
            : Loc.GetString("oxyd-sleeper-no-beaker");
        EjectBeakerButton.Disabled = !state.HasBeaker;
    }
}
