using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris sleeper NanoUI (sleeper.tmpl on the dark skin): occupant name, Critical Health /
/// Organ Health rows, one displayBar per damage group (good &lt;= 25, average &lt;= 50,
/// bad above), the dialysis toggle + eject links, then the fixed chem menu rows
/// (name + "Occupant: N units" + Inject 5 / Inject 10 pills) and the beaker free-space
/// line with an Eject link.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydSleeperWindow : FancyWindow
{
    public event Action<string, float>? InjectRequested;
    public event Action? EjectRequested;
    public event Action? EjectBeakerRequested;
    public event Action? ToggleDialysisRequested;

    public OxydSleeperWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));
    }

    private static Color BarColor(float damage) => damage switch
    {
        > 50f => ErisSurgeryColors.BarBad,
        > 25f => ErisSurgeryColors.BarAverage,
        _ => ErisSurgeryColors.BarGood,
    };

    public void UpdateState(OxydSleeperState state)
    {
        Content.RemoveAllChildren();

        if (!state.HasOccupant)
        {
            Content.AddChild(new ErisItemLabel(Loc.GetString("oxyd-sleeper-empty")));
            BuildBeakerBox(state);
            return;
        }

        // itemLabel: occupant name
        var nameLabel = new ErisItemLabel(state.OccupantName);
        Content.AddChild(nameLabel);

        // Status rows.
        var statusRow = new ErisSpecRow(Loc.GetString("oxyd-sleeper-status-label"));
        var (statusText, statusColor) = !state.Alive
            ? (Loc.GetString("oxyd-sleeper-status-dead"), ErisSurgeryColors.BadText)
            : state.OccupantCritical
                ? (Loc.GetString("oxyd-sleeper-status-crit"), ErisSurgeryColors.BarAverage)
                : (Loc.GetString("oxyd-sleeper-status-alive"), ErisSurgeryColors.GoodText);
        statusRow.AddValue(new Label
        {
            Text = statusText,
            FontColorOverride = statusColor,
        });
        Content.AddChild(statusRow);

        var critRow = new ErisSpecRow(Loc.GetString("oxyd-sleeper-crit-health"));
        critRow.AddValue(new Label
        {
            Text = $"{(int) state.OccupantHealth}%",
            FontColorOverride = ErisSurgeryColors.Text,
        });
        Content.AddChild(critRow);

        var organRow = new ErisSpecRow(Loc.GetString("oxyd-sleeper-organ-health"));
        organRow.AddValue(new Label
        {
            Text = $"{(int) state.OrganHealth}%",
            FontColorOverride = ErisSurgeryColors.Text,
        });
        Content.AddChild(organRow);

        // Eris "Pulse" stat row (get_pulse classification).
        var pulseRow = new ErisSpecRow(Loc.GetString("oxyd-sleeper-pulse"));
        var (pulseKey, pulseColor) = state.Pulse switch
        {
            OxydPulse.None => ("oxyd-pulse-none", ErisSurgeryColors.BadText),
            OxydPulse.Thready => ("oxyd-pulse-thready", ErisSurgeryColors.BarAverage),
            OxydPulse.Irregular => ("oxyd-pulse-irregular", ErisSurgeryColors.BarAverage),
            _ => ("oxyd-pulse-norm", ErisSurgeryColors.GoodText),
        };
        pulseRow.AddValue(new Label
        {
            Text = Loc.GetString(pulseKey),
            FontColorOverride = pulseColor,
        });
        Content.AddChild(pulseRow);

        // Damage displayBars in a 2x2 grid like the Eris row.
        var bars = new GridContainer { Columns = 2, HorizontalExpand = true, VSeparationOverride = 4 };
        AddBar(bars, Loc.GetString("oxyd-sleeper-bar-brute"), state.BruteLoss);
        AddBar(bars, Loc.GetString("oxyd-sleeper-bar-burn"), state.BurnLoss);
        AddBar(bars, Loc.GetString("oxyd-sleeper-bar-resp"), state.OxyLoss);
        AddBar(bars, Loc.GetString("oxyd-sleeper-bar-toxin"), state.ToxinLoss);
        Content.AddChild(bars);

        // Dialysis + eject links row.
        var links = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 8,
        };
        var dialysis = new ErisLink(Loc.GetString(state.Filtering
            ? "oxyd-sleeper-dialysis-active"
            : "oxyd-sleeper-dialysis-inactive"));
        dialysis.OnPressed += _ => ToggleDialysisRequested?.Invoke();
        if (!state.FilterAvailable)
            dialysis.SetDisabledLook();
        links.AddChild(dialysis);

        var eject = new ErisLink(Loc.GetString("oxyd-sleeper-eject-occupant"));
        eject.OnPressed += _ => EjectRequested?.Invoke();
        links.AddChild(eject);
        Content.AddChild(links);

        // Chem menu: name | Occupant: N units | Inject 5 | Inject 10
        var chemScroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        var chemBox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 2,
        };
        chemScroll.AddChild(chemBox);
        var i = 0;
        foreach (var chem in state.Chems)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                HorizontalExpand = true,
                MinHeight = 24,
            };
            var name = new ErisItemLabel(Loc.GetString(chem.Name));
            name.SetWidth = 110f;
            name.ClipText = true;
            row.AddChild(name);

            var units = new ErisSubLabel(Loc.GetString("oxyd-sleeper-in-patient",
                ("units", (int) chem.InPatient)));
            units.SetWidth = 110f;
            units.ClipText = true;
            row.AddChild(units);

            row.AddChild(new Control { HorizontalExpand = true });

            foreach (var dose in new[] { 5f, 10f })
            {
                if (dose > chem.DoseSize)
                    continue;
                var d = dose;
                var inject = new ErisLink(Loc.GetString("oxyd-sleeper-inject-units",
                    ("units", (int) d)));
                var local = chem.Reagent;
                inject.OnPressed += _ => InjectRequested?.Invoke(local, d);
                if (!chem.Enabled)
                {
                    inject.SetDisabledLook();
                    if (chem.DisabledReason != null)
                        inject.ToolTip = chem.DisabledReason;
                }
                row.AddChild(inject);
            }

            chemBox.AddChild(ErisCandystripe.Wrap(row, i++));
        }
        Content.AddChild(chemScroll);

        BuildBeakerBox(state);
    }

    private static void AddBar(GridContainer grid, string name, float damage)
    {
        var box = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        var label = new ErisSubLabel(name);
        label.SetWidth = 90f;
        box.AddChild(label);
        var bar = new ErisBar();
        bar.HorizontalExpand = true;
        bar.SetValue(Math.Clamp(damage / 100f, 0f, 1f), BarColor(damage),
            $"{(int) Math.Max(0f, damage)}");
        box.AddChild(bar);
        grid.AddChild(box);
    }

    private void BuildBeakerBox(OxydSleeperState state)
    {
        var box = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 8,
        };
        var free = state.HasBeaker ? state.BeakerMaxVolume - state.BeakerVolume : 0f;
        var label = new ErisSubLabel(state.HasBeaker
            ? Loc.GetString("oxyd-sleeper-beaker-free", ("units", (int) free))
            : Loc.GetString("oxyd-sleeper-no-beaker"));
        label.HorizontalExpand = true;
        box.AddChild(label);

        var ejectBeaker = new ErisLink(Loc.GetString("oxyd-sleeper-eject-beaker"));
        ejectBeaker.OnPressed += _ => EjectBeakerRequested?.Invoke();
        if (!state.HasBeaker)
            ejectBeaker.SetDisabledLook();
        box.AddChild(ejectBeaker);
        Content.AddChild(box);
    }
}
