using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class OxydAutodocWindow : FancyWindow
{
    public event Action<OxydSurgeryStep>? EnqueueRequested;
    public event Action? ClearRequested;
    public event Action? StartRequested;
    public event Action? EjectRequested;

    public OxydAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        StartButton.OnPressed += _ => StartRequested?.Invoke();
        ClearButton.OnPressed += _ => ClearRequested?.Invoke();
        EjectButton.OnPressed += _ => EjectRequested?.Invoke();
    }

    public void UpdateState(OxydAutodocState state)
    {
        OccupantLabel.Text = state.HasOccupant
            ? Loc.GetString("oxyd-autodoc-occupant", ("name", state.OccupantName))
            : Loc.GetString("oxyd-autodoc-empty");

        StatusLabel.Text = state.Running
            ? Loc.GetString("oxyd-autodoc-running", ("step", state.ActiveStepName ?? "?"))
            : Loc.GetString("oxyd-autodoc-idle");

        AvailableSteps.RemoveAllChildren();
        foreach (var proc in state.Available)
        {
            var step = proc.Step;
            var button = new Button { Text = proc.Name, Disabled = !proc.Applicable || state.Running };
            button.OnPressed += _ => EnqueueRequested?.Invoke(step);
            AvailableSteps.AddChild(button);
        }

        QueueList.RemoveAllChildren();
        foreach (var step in state.Queue)
        {
            QueueList.AddChild(new Label { Text = step.ToString() });
        }

        StartButton.Disabled = state.Running || !state.HasOccupant || state.Queue.Count == 0;
        ClearButton.Disabled = state.Running || state.Queue.Count == 0;
        EjectButton.Disabled = state.Running;
    }
}
