using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris autodoc_capitalism.tmpl: greeting + balance row with an eject-credits link,
/// the costed action row ("Scan: N" / "Process all: N" / "Process picked: N" /
/// red "Abort"), a "SURGERY IN PROCESS" banner + ErisBar while running, the
/// Overall Status card (damage + blood bars and global ops) and per-organ cards
/// with costed op links that show a check when picked.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydAutodocWindow : FancyWindow
{
    public event Action? ScanRequested;
    public event Action? ProcessAllRequested;
    public event Action? ProcessPickedRequested;
    public event Action? AbortRequested;
    public event Action? EjectRequested;
    public event Action? EjectCreditsRequested;
    public event Action<int, OxydAutodocOp>? ToggleRequested;

    private readonly ErisLink _scan;
    private readonly ErisLink _processAll;
    private readonly ErisLink _processPicked;
    private readonly ErisLink _abort;
    private readonly ErisLink _eject;
    private readonly ErisLink _ejectCredits;
    private readonly Label _balance;
    private readonly Label _running;
    private readonly ErisBar _progress;
    private readonly ScrollContainer _scroll;
    private readonly BoxContainer _entries;

    public OxydAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));

        // Greeting/balance row.
        var top = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 8 };
        _balance = new Label { FontColorOverride = ErisSurgeryColors.ItemLabelText, HorizontalExpand = true };
        top.AddChild(_balance);
        _ejectCredits = new ErisLink(Loc.GetString("oxyd-autodoc-eject-credits"));
        _ejectCredits.OnPressed += _ => EjectCreditsRequested?.Invoke();
        top.AddChild(_ejectCredits);
        Content.AddChild(top);

        // Action row.
        var actions = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
        _scan = new ErisLink("");
        _scan.OnPressed += _ => ScanRequested?.Invoke();
        actions.AddChild(_scan);
        _processAll = new ErisLink("");
        _processAll.OnPressed += _ => ProcessAllRequested?.Invoke();
        actions.AddChild(_processAll);
        _processPicked = new ErisLink("");
        _processPicked.OnPressed += _ => ProcessPickedRequested?.Invoke();
        actions.AddChild(_processPicked);
        _abort = new ErisLink(Loc.GetString("oxyd-autodoc-abort"), red: true);
        _abort.OnPressed += _ => AbortRequested?.Invoke();
        actions.AddChild(_abort);
        Content.AddChild(actions);

        _running = new Label { FontColorOverride = ErisSurgeryColors.BadText };
        Content.AddChild(_running);
        _progress = new ErisBar { HorizontalExpand = true };
        Content.AddChild(_progress);

        _entries = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        _scroll = new ScrollContainer { VerticalExpand = true, HorizontalExpand = true };
        _scroll.AddChild(_entries);
        Content.AddChild(_scroll);

        var bottom = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 8 };
        _eject = new ErisLink(Loc.GetString("oxyd-autodoc-eject"));
        _eject.OnPressed += _ => EjectRequested?.Invoke();
        bottom.AddChild(_eject);
        Content.AddChild(bottom);
    }

    private static string OpName(OxydAutodocOp op) =>
        Loc.GetString($"oxyd-autodoc-op-{op.ToString().ToLowerInvariant()}");

    private static void SetDisabled(ErisLink link, bool disabled, bool red = false)
    {
        if (disabled)
            link.SetDisabledLook();
        else
            link.SetEnabledLook(red);
    }

    public void UpdateState(OxydAutodocState state)
    {
        _balance.Text = Loc.GetString("oxyd-autodoc-balance", ("balance", state.Balance));
        _scan.Text = Loc.GetString("oxyd-autodoc-scan", ("cost", state.ScanCost));
        _processAll.Text = Loc.GetString("oxyd-autodoc-process-all", ("cost", state.TotalCost));
        _processPicked.Text = Loc.GetString("oxyd-autodoc-process-picked", ("cost", state.CustomCost));

        var hasOccupant = state.HasOccupant;
        var hasNotes = state.Organs.Count > 0 || state.Global.Available.Count > 0;
        SetDisabled(_scan, state.Running || !hasOccupant);
        SetDisabled(_processAll, state.Running || !hasOccupant || !hasNotes);
        SetDisabled(_processPicked, state.Running || !hasOccupant || !hasNotes || state.CustomCost <= 0);
        SetDisabled(_abort, !state.Running, red: true);
        SetDisabled(_eject, state.Running);
        SetDisabled(_ejectCredits, state.Running || state.Balance <= 0);

        // "SURGERY IN PROCESS" banner + progress bar while running.
        _running.Text = state.Running ? Loc.GetString("oxyd-autodoc-in-progress") : "";
        _progress.Visible = state.Running;
        if (state.Running)
            _progress.SetValue(state.Progress, ErisSurgeryColors.BarDefault, $"{(int) (state.Progress * 100f)}%");

        _entries.RemoveAllChildren();

        if (!hasOccupant)
        {
            _entries.AddChild(new ErisItemLabel(Loc.GetString("oxyd-autodoc-empty")));
            return;
        }

        if (!hasNotes)
        {
            _entries.AddChild(new ErisItemLabel(Loc.GetString("oxyd-autodoc-no-scan")));
            return;
        }

        // Overall status card (Eris toxnote): displayBars + global ops.
        var gcard = new ErisPanel { HorizontalExpand = true };
        var gv = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 4,
        };
        gv.AddChild(new ErisItemLabel(Loc.GetString("oxyd-autodoc-overall")));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-brute"), state.BruteLoss, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-burn"), state.BurnLoss, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-toxin"), state.ToxinLoss, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-oxy"), state.OxyLoss, invert: true));
        gv.AddChild(Bar(Loc.GetString("oxyd-autodoc-blood-level"), state.BloodPercent, invert: false));
        AddOpLinks(gv, state.Global, state);
        gcard.AddChild(gv);
        _entries.AddChild(gcard);

        // Per-organ cards with costed op links.
        foreach (var organ in state.Organs)
        {
            var card = new ErisPanel { HorizontalExpand = true };
            var v = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 4,
            };
            v.AddChild(new ErisItemLabel(organ.Name));
            var damage = organ.Internal
                ? Loc.GetString("oxyd-autodoc-inner-damage", ("dmg", (int) organ.InnerDamage))
                : Loc.GetString("oxyd-autodoc-organ-damage",
                    ("brute", (int) organ.BruteDamage), ("burn", (int) organ.BurnDamage));
            v.AddChild(new ErisSubLabel(damage));
            AddOpLinks(v, organ, state);
            card.AddChild(v);
            _entries.AddChild(card);
        }
    }

    private void AddOpLinks(BoxContainer box, OxydAutodocEntry entry, OxydAutodocState state)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        foreach (var op in entry.Available)
        {
            var picked = entry.Picked.Contains(op);
            var cost = state.OpCosts.GetValueOrDefault(op);
            var id = entry.Id;
            var link = new ErisLink(Loc.GetString("oxyd-autodoc-op-cost",
                ("op", OpName(op)), ("cost", cost)) + (picked ? " ✓" : ""));
            link.OnPressed += _ => ToggleRequested?.Invoke(id, op);
            if (state.Running)
                link.SetDisabledLook();
            else if (picked)
                link.SetSelectedLook();
            row.AddChild(link);
        }
        box.AddChild(row);
    }

    private static Color DamageBarColor(float damage) => damage switch
    {
        > 50f => ErisSurgeryColors.BarBad,
        > 25f => ErisSurgeryColors.BarAverage,
        _ => ErisSurgeryColors.BarGood,
    };

    private static Control Bar(string name, float value, bool invert)
    {
        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
        var label = new ErisSubLabel(name);
        label.SetWidth = 110f;
        label.ClipText = true;
        row.AddChild(label);
        var bar = new ErisBar { HorizontalExpand = true };
        var shown = invert ? Math.Clamp(100f - value, 0f, 100f) : Math.Clamp(value, 0f, 100f);
        bar.SetValue(shown / 100f, invert ? DamageBarColor(value) : ErisSurgeryColors.BarDefault,
            $"{(int) value}");
        row.AddChild(bar);
        return row;
    }
}
