using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.Maths;

namespace Content.Client._Oxyd.Medical.UI;

/// <summary>
/// Eris centrifuge NanoUI (centrifuge.tmpl): "Control panel" gold header, a
/// "Start spin cycle" link, an Idle/Working status line, the 5/10/15/30/60
/// duration pills, the "Supported up to N separation beakers" caption, then the
/// main beaker contents with per-reagent target dropdowns and the separation
/// beaker columns (each with contents + Eject).
/// Electrolyzer mode (electrolyzer.tmpl): On/Off pills plus a two-column
/// "Beaker | Separation Beaker" statusDisplay layout.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OxydChemProcessorWindow : FancyWindow
{
    public event Action<string, int>? TargetSet;
    public event Action? StartRequested;
    public event Action<float>? DurationSet;
    public event Action<bool>? RunningSet;
    public event Action<int>? EjectRequested;

    private static readonly float[] Durations = { 5f, 10f, 15f, 30f, 60f };

    public OxydChemProcessorWindow()
    {
        RobustXamlLoader.Load(this);
        Body.PanelOverride = new StyleBoxFlat(new Color(0.15f, 0.15f, 0.15f));
    }

    public void UpdateState(OxydChemProcessorState state)
    {
        Content.RemoveAllChildren();
        switch (state.Mode)
        {
            case OxydChemProcessorMode.Centrifuge:
                BuildCentrifuge(state);
                break;
            case OxydChemProcessorMode.Electrolyzer:
                BuildElectrolyzer(state);
                break;
        }
    }

    // ---------------------- Centrifuge (centrifuge.tmpl) ----------------------

    private void BuildCentrifuge(OxydChemProcessorState state)
    {
        Content.AddChild(new ErisItemLabel(Loc.GetString("oxyd-processor-control")));

        var start = new ErisLink(Loc.GetString("oxyd-processor-start-spin"));
        start.OnPressed += _ => StartRequested?.Invoke();
        if (state.Working || !state.HasMainBeaker)
            start.SetDisabledLook();
        Content.AddChild(start);

        Content.AddChild(new ErisSubLabel(Loc.GetString("oxyd-processor-status",
            ("status", Loc.GetString(state.Working
                ? "oxyd-processor-status-working"
                : "oxyd-processor-status-idle")))));

        // 5/10/15/30/60 duration pills.
        var durationRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };
        foreach (var d in Durations)
        {
            var dur = d;
            var pill = new ErisLink($"{(int) d}");
            if (Math.Abs(state.Duration - d) < 0.01f)
                pill.SetSelectedLook();
            else
                pill.SetUnselectedLook();
            pill.OnPressed += _ => DurationSet?.Invoke(dur);
            durationRow.AddChild(pill);
        }
        Content.AddChild(durationRow);

        Content.AddChild(new ErisSubLabel(Loc.GetString("oxyd-processor-sep-rating",
            ("count", OxydChemProcessorComponent.SeparationBeakerCount))));

        // Main beaker contents: name (Nu) + target-beaker dropdown.
        var mainBox = new ErisStatusBox { HorizontalExpand = true, VerticalExpand = true };
        var mainContent = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 2,
            HorizontalExpand = true,
        };
        mainBox.AddChild(new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            Children = { mainContent },
        });
        mainContent.AddChild(new ErisItemLabel(Loc.GetString("oxyd-processor-main-beaker")));
        if (!state.HasMainBeaker)
        {
            mainContent.AddChild(new ErisSubLabel(Loc.GetString("oxyd-processor-no-beaker")));
        }
        else
        {
            foreach (var reagent in state.MainContents)
            {
                var row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    SeparationOverride = 6,
                };
                row.AddChild(new Label
                {
                    Text = $"{reagent.Name} ({reagent.Volume:0.#}u)",
                    FontColorOverride = ErisSurgeryColors.Text,
                    HorizontalExpand = true,
                });
                var option = new OptionButton();
                for (var i = -1; i < OxydChemProcessorComponent.SeparationBeakerCount; i++)
                {
                    var label = i < 0
                        ? Loc.GetString("oxyd-processor-leave")
                        : Loc.GetString("oxyd-processor-beaker-n", ("n", i + 1));
                    option.AddItem(label, i + 1);
                }
                option.TrySelectId(reagent.TargetBeaker + 1);
                option.Disabled = state.Working;
                var id = reagent.Id;
                option.OnItemSelected += args => TargetSet?.Invoke(id, args.Id - 1);
                row.AddChild(option);
                mainContent.AddChild(row);
            }
        }
        Content.AddChild(mainBox);

        // Separation beaker columns.
        var sepRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        for (var i = 0; i < state.SeparationBeakers.Count; i++)
        {
            var beaker = state.SeparationBeakers[i];
            var index = i;
            var box = new ErisStatusBox { HorizontalExpand = true };
            var col = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 4,
            };
            box.AddChild(col);
            col.AddChild(new ErisItemLabel(Loc.GetString("oxyd-processor-beaker-n", ("n", i + 1))));
            col.AddChild(new ErisSubLabel(beaker.Present
                ? Loc.GetString("oxyd-processor-beaker-status", ("n", i + 1), ("vol", (int) beaker.Volume))
                : Loc.GetString("oxyd-processor-beaker-empty", ("n", i + 1))));
            foreach (var content in beaker.Contents)
            {
                col.AddChild(new Label
                {
                    Text = $"{content.Name} ({content.Volume:0.#}u)",
                    FontColorOverride = ErisSurgeryColors.Text,
                });
            }
            var eject = new ErisLink(Loc.GetString("oxyd-processor-eject"));
            eject.OnPressed += _ => EjectRequested?.Invoke(index);
            if (!beaker.Present || state.Working)
                eject.SetDisabledLook();
            col.AddChild(eject);
            sepRow.AddChild(box);
        }
        Content.AddChild(sepRow);

        var ejectMain = new ErisLink(Loc.GetString("oxyd-processor-eject-main"));
        ejectMain.OnPressed += _ => EjectRequested?.Invoke(-1);
        if (state.Working || !state.HasMainBeaker)
            ejectMain.SetDisabledLook();
        Content.AddChild(ejectMain);
    }

    // ---------------------- Electrolyzer (electrolyzer.tmpl) ----------------------

    private void BuildElectrolyzer(OxydChemProcessorState state)
    {
        // On/Off pills: On stays lit while the continuous mode is running.
        var pills = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };
        var on = new ErisLink(Loc.GetString("oxyd-processor-on"));
        var off = new ErisLink(Loc.GetString("oxyd-processor-off"));
        if (state.Continuous)
        {
            on.SetSelectedLook();
            off.SetUnselectedLook();
        }
        else
        {
            on.SetUnselectedLook();
            off.SetSelectedLook();
        }
        on.OnPressed += _ => RunningSet?.Invoke(true);
        off.OnPressed += _ => RunningSet?.Invoke(false);
        pills.AddChild(on);
        pills.AddChild(off);
        Content.AddChild(pills);

        // Two columns: Beaker | Separation Beaker.
        var cols = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        cols.AddChild(BeakerColumn(
            Loc.GetString("oxyd-processor-main-beaker"),
            state.HasMainBeaker,
            state.MainContents,
            -1, state));

        var sep = state.SeparationBeakers.Count > 0 ? state.SeparationBeakers[0] : null;
        var sepBox = new ErisStatusBox { HorizontalExpand = true, VerticalExpand = true };
        var sepCol = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 4,
        };
        sepBox.AddChild(sepCol);
        sepCol.AddChild(new ErisItemLabel(Loc.GetString("oxyd-processor-sep-beaker")));
        if (sep is { Present: true })
        {
            sepCol.AddChild(new ErisSubLabel($"{(int) sep.Volume} / {(int) sep.MaxVolume}u"));
            foreach (var c in sep.Contents)
            {
                sepCol.AddChild(new Label
                {
                    Text = $"{c.Name} ({c.Volume:0.#}u)",
                    FontColorOverride = ErisSurgeryColors.Text,
                });
            }
            var eject = new ErisLink(Loc.GetString("oxyd-processor-eject"));
            eject.OnPressed += _ => EjectRequested?.Invoke(0);
            if (state.Working)
                eject.SetDisabledLook();
            sepCol.AddChild(eject);
        }
        else
        {
            sepCol.AddChild(new ErisSubLabel(Loc.GetString("oxyd-processor-beaker-empty", ("n", 1))));
        }
        cols.AddChild(sepBox);
        Content.AddChild(cols);
    }

    private Control BeakerColumn(string title, bool present,
        List<OxydChemProcessorReagent> contents, int ejectIndex, OxydChemProcessorState state)
    {
        var box = new ErisStatusBox { HorizontalExpand = true, VerticalExpand = true };
        var col = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 4,
        };
        box.AddChild(col);
        col.AddChild(new ErisItemLabel(title));
        if (!present)
        {
            col.AddChild(new ErisSubLabel(Loc.GetString("oxyd-processor-no-beaker")));
            return box;
        }
        foreach (var c in contents)
        {
            col.AddChild(new Label
            {
                Text = $"{c.Name} ({c.Volume:0.#}u)",
                FontColorOverride = ErisSurgeryColors.Text,
            });
        }
        var eject = new ErisLink(Loc.GetString("oxyd-processor-eject"));
        eject.OnPressed += _ => EjectRequested?.Invoke(ejectIndex);
        if (state.Working)
            eject.SetDisabledLook();
        col.AddChild(eject);
        return box;
    }
}
